import React, { createContext, useState, useContext, useEffect } from 'react';

const LanguageContext = createContext({
  language: 'en',
  setLanguage: () => {},
  toggleLanguage: () => {},
  t: (key) => key,
  tf: (key) => key,
  isEnglish: true,
  isChinese: false,
});

export function useLanguage() {
  return useContext(LanguageContext);
}

function normalizeLanguageCode(input) {
  const raw = String(input || '').trim();
  const lower = raw.toLowerCase();
  if (lower === 'en' || lower.startsWith('en-') || lower.startsWith('en_')) return 'en';
  if (lower === 'zh' || lower.startsWith('zh-') || lower.startsWith('zh_')) return 'zh';
  return 'en';
}

// Translation dictionary
const translations = {
  en: {
    // Branding
    appName: "ChemLeung HKDSE MCQ Practice Platform",
    tagline: "HKDSE Chemistry Practice",
    
    // Navigation
    nav: {
      dashboard: "Dashboard",
      practice: "Practice",
      leaderboard: "Leaderboard",
      history: "History",
      profile: "Profile",
      logout: "Logout",
    },

    header: {
      tokens: "diamonds",
      myHistory: "My History",
      tokenHistory: "Diamond History",
      logoutWarning: "You will be logged out of your account. Any unsaved progress will be lost.",
      confirmLogoutInQuiz: "Are you sure you want to logout?\n\n⚠️ You are in the middle of a quiz. Your progress will be lost!",
      confirmLeaveQuiz: "Are you sure you want to leave the quiz?\n\n⚠️ Your current progress will be lost!",
    },
    
    // Dashboard
    dashboard: {
      welcomeBack: "Welcome back",
      totalAttempts: "Total Attempts",
      overallAccuracy: "Overall Accuracy",
      questionsSolved: "Questions Solved",
      correctAnswers: "Correct Answers",
      studyStreak: "Study Streak",
      days: "days",
      startNewQuiz: "Start New Quiz",
      viewLeaderboard: "View Leaderboard",
      recentAttempts: "Recent Attempts",
      noAttempts: "No attempts yet!",
      takeFirstQuiz: "Take Your First Quiz",
      browseForm: "Browse Forum",
      mistakeNotebook: "Mistake Notebook",
      
      // Learning Insights
      learningInsights: "Learning Insights",
      viewAll: "View All",
      noLearningData: "No learning data yet",
      startLearningJourney: "Start your learning journey",
      startPracticing: "Start practicing to see insights",
      availableFeatures: "Available Features",
      learningFeatures: "Learning Features",
      exploreLearningNotebook: "Explore Learning Notebook",
      openLearningNotebook: "Open Learning Notebook",
      
      // Feature titles and descriptions
      learningAnalytics: "Learning Analytics",
      learningAnalyticsDesc: "Track progress and performance patterns",
      mistakeDeckWithSRS: "Mistake Deck with SRS",
      mistakeDeckWithSRSDesc: "Spaced repetition for optimal learning",
      masteryArchiveSystem: "Mastery Archive System",
      masteryArchiveSystemDesc: "Organized collection of mastered topics",
      progressTrackingCharts: "Progress Tracking & Charts",
      progressTrackingChartsDesc: "Visual insights into learning journey",
      
      // Stats
      totalMistakes: "Total Mistakes",
      topics: "Topics",
      repeated: "Repeated",
      topTopicsToFocus: "Top Topics to Focus",
      mistakes: "mistakes",
      density: "density",
      dailyReward: "Daily reward",
      claiming: "Claiming...",
      logout: "Logout",
      confirmLogout: "Confirm Logout",
      areYouSureLogout: "Are you sure you want to logout?",
      needSignInAgain: "You will need to sign in again to access your account and continue practicing.",
      cancel: "Cancel",
      errorLoadingAttempts: "Error Loading Attempts",
      retry: "Retry",
      clickRowFullAnalysis: "Click any row to see full analysis",
      refresh: "Refresh",
      noDataYet: "No data yet",
      completeQuizSeeResults: "Complete a quiz to see your results here",
      timeSpent: "Time spent",
      loadingDashboard: "Loading dashboard...",

      howThisWorks: "How this works",
      priorityReviewTitle: "Priority Review",
      top3UrgentMistakes: "Top 3 Urgent Mistakes (ISRS Algorithm)",
      priorityReviewEmpty: "No mistakes tracked yet. Complete quizzes and log your mistakes to get personalized review recommendations!",
      priorityReviewMechanismTitle: "Priority Review mechanism",
      priorityReviewMechanismDesc: "This panel surfaces the top 3 most urgent mistakes using the ISRS priority score.",
      whatIncreasesPriorityTitle: "What increases priority",
      whatIncreasesPriorityDesc: "More recent wrong attempts, repeated mistakes, and topics you've studied recently.",
      whatQuickFixDoesTitle: "What \"Quick Fix\" does",
      whatQuickFixDoesDesc: "Starts a focused practice session for that specific question so you can fix it immediately.",
      priorityCritical: "Critical",
      priorityHigh: "High",
      priorityMedium: "Medium",
      priorityLow: "Low",
      priorityLabel: "{level} Priority",
      questionTextNotAvailable: "Question text not available",
      attempts: "Attempts",
      correct: "Correct",
      quickFix: "Quick Fix",
      viewFullMistakeNotebook: "View Full Mistake Notebook",

      masteryHealthBarTitle: "Mastery Health Bar",
      ruleOf3Subtitle: "Based on the Rule of 3 system",
      masteryHealthBarMechanismTitle: "Mastery Health Bar mechanism",
      masteryMechanismDesc: "Topics move through 3 states based on correct attempts (the Rule of 3).",
      masteryNewTitle: "New",
      masteryNewDesc: "Not attempted yet.",
      masteryImprovingTitle: "Improving",
      masteryImprovingDesc: "1–2 correct answers.",
      masteryMasteredTitle: "Mastered",
      masteryMasteredDesc: "3+ correct answers.",
      masteryBarExplainer: "The bar shows your syllabus coverage split into these 3 categories.",
      syllabusCoverage: "Syllabus Coverage",
      topicsTrackedCount: "{count} Topics Tracked",
      unseenTooltip: "{pct}% Unseen ({count} topics)",
      improvingTooltip: "{pct}% Improving ({count} topics)",
      masteredTooltip: "{pct}% Mastered ({count} topics)",

      quickStatsTitle: "Quick Stats",
      quickStatsMechanismTitle: "Quick Stats mechanism",
      quickStatsMechanismDesc: "This section summarizes your learning momentum and progress at a glance.",
      quickStatsStudyStreakTitle: "Study Streak",
      quickStatsStudyStreakDesc: "Counts consecutive days you studied (based on recent activity).",
      quickStatsTopicsMasteredTitle: "Topics Mastered",
      quickStatsTopicsMasteredDesc: "How many topics have reached the mastered threshold in the mastery system.",
      quickStatsInProgressTitle: "In Progress",
      quickStatsInProgressDesc: "Topics you’ve started but haven’t mastered yet (keep practicing to push them over the line).",

      quizSessionsCount: "{count} Quiz Session(s)",
      correctOutOfTotal: "{correct}/{total} Correct",
      clickAnyAttempt: "Click any attempt",
      toSeeDetailedAnalysis: "to see detailed analysis and insights",

      priorityReviewAiStudySuggestionTitle: "Priority Review: AI Study Suggestion",
      aiStudySuggestionsEmpty: "No AI suggestions yet. Keep practicing to unlock personalized recommendations.",
      aiSuggestionsMechanismTitle: "AI Study Suggestions",
      aiSuggestionsMechanismDesc: "These suggestions are generated from your recent performance by topic/subtopic. Accepting one adds a recommended study session into your calendar. The AI analyzes your accuracy trends and suggests topics that need more practice.",
      aiStudySuggestionsMechanismDescLong: "The AI analyzes your accuracy trends and suggests topics that need more practice. This helps you focus on areas where you need improvement, making your study sessions more efficient.",
      srsReviewTitle: "SRS Review",
      srsReviewSubtitle: "Master your weaknesses",
      srsReviewDesc: "Turn mistakes into strengths with spaced repetition.",
      srsReviewMechanismTitle: "SRS Review mechanism",
      srsReviewMechanismDesc: "SRS (Spaced Repetition System) schedules reviews at optimal intervals: 1st review after 1 day, 2nd after 6 days, then interval × ease factor (2.5 default). Wrong answers reset progress. After 5 successful reviews, the card graduates to Mastery Archive.",
      srsReviewMechanismDescLong: "SRS (Spaced Repetition System) schedules reviews at optimal intervals: 1st review after 1 day, 2nd after 6 days, then interval × ease factor (2.5 default). Wrong answers reset progress. After 5 successful reviews, the card graduates to Mastery Archive. This helps solidify your knowledge and prevent forgetting.",

      masteryHealthBarTitle: "Mastery Health Bar",
      ruleOf3Subtitle: "Based on the Rule of 3 system",
      masteryHealthBarMechanismTitle: "Mastery Health Bar mechanism",
      masteryMechanismDesc: "Topics move through 3 states based on correct attempts (the Rule of 3).",
      masteryNewTitle: "New",
      masteryNewDesc: "Not attempted yet.",
      masteryImprovingTitle: "Improving",
      masteryImprovingDesc: "1–2 correct answers.",
      masteryMasteredTitle: "Mastered",
      masteryMasteredDesc: "3+ correct answers.",
      masteryBarExplainer: "The bar shows your syllabus coverage split into these 3 categories.",
      syllabusCoverage: "Syllabus Coverage",
      topicsTrackedCount: "{count} Topics Tracked",
      unseenTooltip: "{pct}% Unseen ({count} topics)",
      improvingTooltip: "{pct}% Improving ({count} topics)",
      masteredTooltip: "{pct}% Mastered ({count} topics)",

      quickStatsTitle: "Quick Stats",
      quickStatsMechanismTitle: "Quick Stats mechanism",
      quickStatsMechanismDesc: "This section summarizes your learning momentum and progress at a glance.",
      quickStatsStudyStreakTitle: "Study Streak",
      quickStatsStudyStreakDesc: "Counts consecutive days you studied (based on recent activity).",
      quickStatsTopicsMasteredTitle: "Topics Mastered",
      quickStatsTopicsMasteredDesc: "How many topics have reached the mastered threshold in the mastery system.",
      quickStatsInProgressTitle: "In Progress",
      quickStatsInProgressDesc: "Topics you’ve started but haven’t mastered yet (keep practicing to push them over the line).",

      quizSessionsCount: "{count} Quiz Session(s)",
      correctOutOfTotal: "{correct}/{total} Correct",
      clickAnyAttempt: "Click any attempt",
      toSeeDetailedAnalysis: "to see detailed analysis and insights",

      priorityReviewAiStudySuggestionTitle: "Priority Review: AI Study Suggestion",
      aiStudySuggestionsEmpty: "No AI suggestions yet. Keep practicing to unlock personalized recommendations.",
      aiSuggestionsMechanismTitle: "AI Study Suggestions",
      aiSuggestionsMechanismDesc: "These suggestions are generated from your recent performance by topic/subtopic. Accepting one adds a recommended study session into your calendar. The AI analyzes your accuracy trends and suggests topics that need more practice.",
      aiHowGeneratesTitle: "How AI Generates Suggestions",
      aiHowGeneratesDesc: "• Analyzes your accuracy trends by topic/subtopic\n• Identifies weak areas (below 60% accuracy)\n• Prioritizes topics you recently struggled with\n• Suggests optimal question counts for practice",
      aiPriorityLevelsTitle: "Priority Levels",
    },

    srs: {
      title: "Spaced Repetition Review",
      failedLoadDueCardsTryAgain: "Failed to load due cards. Please try again.",
      loadingDueCards: "Loading due cards...",
      pleaseSelectAtLeastOne: "Please select at least one question to review.",
      questionsStillLoading: "Questions are still loading. Please wait a moment and try again.",

      questionsNeedReviewCount: "{count} question{plural} need review",
      questionsNeedReviewShownOutOfTotal: "Showing {shown}/{total} due questions",
      reviewMode: "Review Mode",
      quickReview: "Quick Review",
      aiSelectsRandomQuestions: "AI selects random questions",
      defaultBadge: "✓ DEFAULT",
      singleQuestion: "Single Question",
      reviewOneMistake: "Review one mistake",
      customBatch: "Custom Batch",
      selectSpecificCards: "Select specific cards",
      numberOfQuestions: "Number of Questions",
      nQuestions: "{count} Questions",
      allCount: "All ({count})",

      timerSettings: "Timer Settings",
      enableTimer: "Enable Timer",
      showTimer: "Show Timer",
      timedMode75sPerQuestion: "Timed Mode (75s per question)",
      mustAnswerWithin75SecondsPerQuestion: "You must answer within 75 seconds per question",
      timerTracksSpeedNoLimit: "Timer tracks your speed but no time limit",
      noTimerTracking: "No timer tracking",
      timedModeSummary75: "Timed Mode: 75s/question",
      timerTrackingEnabled: "Timer tracking enabled",
      noTimer: "No timer",

      selectCardsToReview: "Select Cards to Review",
      selectedCountOutOfTotal: "{selected} / {total} selected",
      deselectAll: "Deselect All",
      selectAll: "Select All",
      dueLabel: "Due",
      noTopic: "No Topic",
      noDueCardsMatchFilters: "No due cards match your filters",
      questionIdLabel: "Question ID",
      questionIdHelp: "matches your MCQ database ID",
      intervalLabel: "Interval",
      attemptLabel: "Attempt",
      easeLabel: "Ease",

      startQuickReviewCount: "Start Quick Review ({count} Question{plural})",
      startSingleReview: "Start Single Review",
      startBatchReviewCount: "Start Batch Review ({count} Question{plural})",
      
      overdueReviewsNotShown: "You have {count} overdue review{plural} (not shown here)",
    },

    practiceModeLegend: {
      regular: "Regular mode",
      mistakeReview: "Mistake review",
      gameMode: "Game mode",
      timedShort: "Timed",
      untimedShort: "Untimed",
      customShort: "Custom",
      aiDailyShort: "AI Daily",
      srsShort: "SRS",
      millionaireShort: "Millionaire",
    },

    practiceModeCarousel: {
      headerTitle: "Choose Your Practice Mode",
      headerSubtitle: "Select a mode to begin your learning journey",
      previousMode: "Previous mode",
      nextMode: "Next mode",
      startSession: "Start Session",
      clickToSelect: "Click to select",
      selectedLabel: "{mode} Selected",
      selectModeAria: "Select {mode}",

      timedTitle: "Timed Mode",
      timedSubtitle: "1.25 min per question",
      timedDesc: "Perfect for exam simulation",
      marathonTitle: "Untimed Mode",
      marathonSubtitle: "No time pressure",
      marathonDesc: "Take your time and focus",
      aiDailyTitle: "AI Daily Review",
      aiDailySubtitle: "Daily focus set",
      aiDailyDesc: "AI picks 10 questions from your recent weaknesses.",
      aiDailyInfoTitle: "How AI Daily Review works",
      aiDailyInfoBody: "AI Daily Review selects 10 questions from your past wrong answers. It prioritizes questions you missed recently or repeatedly, and balances across topics.",
      mistakeReviewTitle: "Custom Mistake Review",
      mistakeReviewSubtitle: "Master your weaknesses",
      mistakeReviewDesc: "Review your mistakes and turn weaknesses into strengths.",
      srsReviewTitle: "SRS Review",
      srsReviewSubtitle: "Spaced repetition",
      srsReviewDesc: "Review what’s due and strengthen memory.",
      customTitle: "Custom Session",
      customSubtitle: "You decide",
      customDesc: "Choose topics and settings",

      millionaireTitle: "Millionaire Mode",
      millionaireSubtitle: "15 questions ladder",
      millionaireDesc: "One wrong answer ends the run. Earn diamonds by reaching higher questions.",
    },

    millionaire: {
      modeName: "Millionaire",
      questionLabel: "Question",
      tokensUnit: "diamonds",
      tokenLadder: "Diamond Ladder",
      safetyNet: "Safety Net",
      cleared: "Cleared",
      now: "Now",
      amountTokens: "{count} diamonds",

      lifelines: {
        aiTips: "AI Tips",
        fiftyFifty: "50:50",
        chemLeung: "ChemLeung",
      },

      rewardIfClear: "Reward if you clear",
      currentBank: "Current Bank",
      lockIn: "Lock In",
      quit: "Quit",

      periodicTableOfElements: "Periodic Table of Elements",
      periodicTable: "Periodic Table",
      periodicTableAlt: "Periodic Table",
      close: "Close",
      details: "Details",

      overlays: {
        finalDecision: "Final decision",
        confirmQuit: "Confirm quit",
        cashOutToSavePrefix: "Cash out to save your current bank",
        cashOutToSaveSuffix: ",",
        orStayContinue: "or stay and continue the round.",
        cashOutToSave: "Cash out to save your current bank {amount} {unit},",
        cashOut: "Cash out",
        stay: "Stay",

        safeHaven: "Safe haven",
        safetyNetReached: "Safety net reached",
        guaranteedPrefix: "Your",
        guaranteedSuffix: "are now guaranteed.",
        guaranteed: "Your {amount} {unit} are now guaranteed.",
        safeHavenAt: "Safe haven: Q{level}",
        fireRoundWarning: "Fire round ahead! The next 5 questions are timed with fire effects!",
        finalSafetyNet: "Final safety net! You're guaranteed 60 diamonds if you continue!",
        continue: "Continue",

        decision: "Decision",
        correct: "Correct!",
        clearedCurrentReward: "You cleared Q{level}. Current reward:",
        nextQuestion: "Next question",
      },

      gameOver: {
        finalResult: "Final result",
        gameOver: "Game over",
        finalRewardAria: "Final reward",
        cashOutConfirmed: "Cash out confirmed",
        perfectRun: "Perfect run",
        timeUp: "Time's up!",
        betterLuck: "Better luck next time",
        questionsAnswered: "Questions answered",
        outOf: "Out of",
        playAgain: "Play again",
        exitToHome: "Exit to home",
      },

      probability: {
        title: "Probability analysis",
        subtitle: "AI-powered answer distribution",
        basedOn: "Based on analysis patterns, here's the probability distribution:",
        optionLabel: "Option {option}",
        warning: "⚠️ This is a probability estimate, not a guarantee. Use your knowledge!",
        gotIt: "Got it!",
      },

      chemLeung: {
        expert: "Chemistry expert",
        analyzing: "ChemLeung is analyzing the question...",
        defaultAnalysis: "Here's my expert analysis of this question...",
        remember: "Remember, this is guidance - make your final decision!",
        thanks: "Thanks, ChemLeung!",
      },

      errors: {
        startFailed: "Failed to start Millionaire mode",
        tokenUpdateFailed: "Failed to update diamond balance",
      },
    },
    
    // Practice Modes
    practice: {
      selectMode: "Select Practice Mode",
      timed: "Timed Practice",
      timedDesc: "Race against the clock - {minutes} minutes",
      marathon: "Marathon Mode",
      marathonDesc: "Unlimited time - track your progress",
      custom: "Custom Session",
      customDesc: "Choose topics and question count",
      startPractice: "Start Practice",
      selectPracticeMode: "Select Practice Mode",
      chooseHowPractice: "Choose how you want to practice today",
      perQuestion: "min per question",
      perfectForExam: "Perfect for exam simulation with a countdown timer.",
      takeYourTime: "Take your time. We'll track duration but no pressure!",
      chooseSpecificTopics: "Choose specific topics, subtopics, and question count.",
      questions: "Questions:",
      configure: "Configure",
      quizSettingsTitle: "Quiz Settings",
      yourAvailableTopics: "Your Available Topics",
      more: "more",
      noTopicsConfigured: "No topics configured!",
      pleaseSetTopics: "Please set which topics you've learned in your Profile settings.",
      goToProfile: "Go to Profile",
      updateTopics: "Update Topics",
      mistakesToSrsTitle: "Mistakes → SRS",
      mistakesToSrsAlways: "Always",
      mistakesToSrsNever: "Never",
      mistakesToSrsAsk: "Ask",
    },
    
    // Quiz Interface
    quiz: {
      question: "Question",
      questionPrefix: "Q",
      of: "of",
      flagQuestion: "Flag Question",
      unflagQuestion: "Unflag Question",
      periodicTable: "Periodic Table",
      periodicTableAlt: "Periodic Table",
      overview: "Overview",
      previous: "Previous",
      next: "Next",
      submit: "Submit",
      answered: "Answered",
      flagged: "Flagged",
      skipped: "Skipped",
      timeRemaining: "Time Remaining",
      sessionTime: "Session Time",
      totalTime: "Total Time",
      initializingQuiz: "Initializing quiz...",
      type: "Type",
      toSelect: "to select",
      flag: "flag",
      tools: "Tools",
      backToTopics: "Back to Topics",
      periodicTableOfElements: "Periodic Table of Elements",
      time: "Time",
      thisQuestion: "This Question:",
      questionOverview: "Question Overview",
      tip: "Tip:",
      press: "Press",
      pleaseAnswerAll: "Please answer all questions before submitting.",
      finishSubmit: "Finish & Submit",
      confirmBackToTopics: "Are you sure you want to go back to topic selection?\n\n⚠️ ALL YOUR PROGRESS WILL BE LOST!",
      enableTimer: "Enable Timer",
      trackTimeSpent: "Track time spent on questions",
      showTimer: "Show Timer",
      countdown: "Countdown",
      timedMode: "Timed Mode",
      countdownTimer: "Countdown with time limit",
      timeUp: "Time's up! Your quiz will be submitted now.",
    },
    
    // Results
    results: {
      yourPerformance: "Your Performance",
      totalTime: "Total Time",
      averagePerQuestion: "Average per MCQ",
      strengths: "Strengths",
      needsFocus: "Needs Focus",
      detailedReview: "Detailed Review",
      yourAnswer: "Your Answer",
      correctAnswer: "Correct Answer",
      explanation: "Explanation",
      shareReport: "Share Report Card",
      addToNotebook: "Add to Mistake Notebook",
      startNewSession: "Start New Session",
      savingToProfile: "Saving to your profile...",
      savedToProfile: "Saved to your profile!",
      reviewsSaved: "Reviews saved!",
      addMistakesToSrsTitle: "Add mistakes to SRS?",
      addMistakesToSrsBody: "We can add the questions you got wrong into SRS (spaced repetition) so you can review them later.",
      addToSrs: "Add to SRS",
      addingToSrs: "Adding...",
      addedToSrs: "Added to SRS!",
      failedAddToSrs: "Failed to add to SRS. Please try again.",
      saveFailed: "Save Failed",
      continueAnyway: "Continue Anyway",
      resultsSavingLeaveConfirm: "Your quiz results are still being saved. Are you sure you want to leave?",
      resultsMayNotBeSavedLeaveConfirm: "Your results may not be fully saved. Are you sure you want to leave?",
      resultsNotSavedContinueAnywayConfirm: "Your results were not saved. Continue anyway?",
    },

    report: {
      shareReportCard: "Share Report Card",
      downloadPngTitle: "Download as PNG image",
      downloadPdfTitle: "Download as PDF",
      image: "Image",
      pdf: "PDF",
      fileNamePrefix: "ChemLeung-Report",
      website: "www.chemleung.com",
      dismiss: "Dismiss",
      hkDsePracticeReport: "HKDSE Chemistry Practice Report",
      studentName: "Student Name",
      student: "Student",
      topicsCovered: "Topics Covered",
      topicsUnit: "Topics",
      outOf: "out of",
      correctLabel: "Correct",
      correct: "Correct",
      incorrect: "Incorrect",
      timeUsed: "Time Used",
      timeHrsMins: "{h}h {m}m",
      timeMinsSecs: "{m}m {s}s",
      topicBreakdown: "Topic Breakdown",
      generatedBy: "Generated by ChemLeung HKDSE MCQ Practice Platform",
      generating: "Generating report...",
      mayTakeSeconds: "This may take a few seconds",
      reportNotReady: "Report not ready. Please try again.",
      failedCreateImage: "Failed to create image",
      failedExportImageTryPdf: "Failed to export image. Try PDF export instead.",
      failedExportPdfTryImage: "Failed to export PDF. Try image export instead.",
      na: "N/A",
    },
    
    // Profile
    profile: {
      profileSettings: "Profile Settings",
      yourStatistics: "Your Statistics",
      displayName: "Display Name",
      email: "Email Address",
      schoolLevel: "School Level (Form)",
      studyLevel: "Current Study Level",
      memberSince: "Member Since",
      saveChanges: "Save Changes",
      topicExceptions: "Topic Exceptions",
      unlockTopic: "Unlock Topic",
      lockTopic: "Lock Topic",
      manageAccount: "Manage your account and learning preferences",
      totalAttempts: "Total Attempts",
      overallAccuracy: "Overall Accuracy",
      questionsSolved: "Questions Solved",
      accountInformation: "Account Information",
      profileUpdated: "Profile updated successfully!",
      failedUpdate: "Failed to update profile. Please try again.",
      enterYourName: "Enter your name",
      emailCannotChange: "Email address cannot be changed",
      selectCurrentForm: "Select your current form (S4, S5, or S6)",
      topicsLearnedUpTo: "Topics Learned Up To",
      selectHighestTopic: "Select the highest topic number you've learned. For example, '08' means you have learned topics 01-08.",
      topicExceptionsLabel: "Topic Exceptions",
      clickToExclude: "Click topics to exclude them from practice",
      yourAvailableTopicsCount: "Your Available Topics",
      theseTopicsWillAppear: "These topics will appear in practice mode",
      saving: "Saving...",
      profilePicture: "Profile Picture",
      preview: "Preview",
      onlyOwnedItems: "Only items you own (or free items) can be used.",
      icon: "Icon",
      background: "Background",
    },

    // Leaderboard
    leaderboard: {
      title: "Leaderboard",
      weeklyTitle: "Weekly Leaderboard",
      thisWeek: "This Week",
      thisMonth: "This Month",
      allTime: "All Time",
      yourRank: "Your Rank",
      you: "You",
      rankAriaLabel: "Rank {rank}",
      rankTitle: "#{rank}",
      noRankLastWeek: "No rank last week",
      noRankLastMonth: "No rank last month",
      alreadyClaimed: "Already claimed",
      tokensAwarded: "+{count} diamonds!",
      noReward: "No reward",
      claimFailed: "Claim failed",
      claimReward: "Claim Reward",
      claimed: "Claimed",
      claimNow: "Claim Now",
      claimedThisPeriod: "Claimed this period",
      notEligible: "Not eligible",
      learnMore: "Learn more",
      attempts: "attempts",
      questions: "questions",
      seeHowYouRank: "See how you rank against other students",
      noDataYet: "No data yet",
      beFirstComplete: "Be the first to complete a quiz!",
      howRankingsWork: "How rankings work:",
      averageScoreLast7: "Average score from all attempts in the last 7 days",
      averageScoreLast30: "Average score from all attempts in the last 30 days",
      overallAccuracyAllTime: "Overall accuracy across all attempts ever",
      formLevel: "S4/S5/S6 = form level",
      flameStreak: "Flame = consecutive study days",
    },

    // Token Log
    tokenLog: {
      title: "Diamond History",
      subtitle: "Track your earnings and purchases",
      totalEarned: "Total Earned",
      totalSpent: "Total Spent",
      allTransactions: "All Transactions",
      gains: "Gains",
      spends: "Spends",
      recentTransactionsCount: "Recent Transactions ({count})",
      noTransactionsYet: "No transactions yet",
      noEarningsYet: "No earnings yet",
      noPurchasesYet: "No purchases yet",
      completeQuizzesToEarn: "Complete quizzes to start earning diamonds!",
      balanceAfterTokens: "Balance after: {balance} diamonds",
      unknown: "Unknown",
    },

    // Calendar / Study Planner
    calendar: {
      addEvent: "Add Event",
      addEventSubtitle: "Schedule an exam or quiz and get a smart study plan",
      addExamQuiz: "Add Exam/Quiz",
      addAnotherEvent: "Add Another Event",
      today: "Today",
      studyPlannerTitle: "Study Planner",
      studyPlannerSubtitle: "Smart scheduling with spaced repetition",
      eventTypes: "Event Types",
      eventTypeMajorExam: "Major Exam",
      eventTypeSmallQuiz: "Small Quiz",
      eventTypeStudySuggestion: "Study Suggestion",
      eventTypeMistakeReview: "SRS Review",
      eventTypeCompletedActivity: "Completed",
      eventsCount: "{count} event{plural}",
      scheduledEventsCount: "{count} scheduled event{plural}",
      noEventsScheduled: "No events scheduled",

      smartStudyCalendar: "Smart Study Calendar",
      smartStudyCalendarFeatures: "Smart Study Calendar features",
      srsReviewMechanismTitle: "SRS Review System",
      srsReviewMechanismDesc: "SRS (Spaced Repetition System) schedules reviews at optimal intervals: 1st review after 1 day, 2nd after 6 days, then interval × ease factor (2.5 default). Wrong answers reset progress. After 5 successful reviews, the card graduates to Mastery Archive.",
      srsFormulaTitle: "SRS Formula",
      srsFormulaBody: "• 1st correct → 1 day\n• 2nd correct → 6 days\n• 3rd+ correct → interval × ease factor (2.5)\n• Wrong answer → reset to 0, 1 day",
      srsGraduationTitle: "Graduation",
      srsGraduationDesc: "After 5 successful reviews, the card enters {archiveName} and is no longer shown in daily reviews.",
      aiSuggestionsByTopicTitle: "AI suggestions (by topic)",
      aiSuggestionsByTopicDesc: "Suggestions are generated from your accuracy trends by topic/subtopic. Accepting one adds a study session into your calendar.",
      examQuizRevisionPlanTitle: "Exam / quiz / revision plan",
      examQuizRevisionPlanDesc: "Add exams and quizzes, then follow a plan that spreads practice and revision across days for steady progress.",
      mechanicsTitle: "Mechanics",
      mechanicsDesc: "Tap a day to see planned items and completions. Completed sessions turn green and stay visible for tracking.",
      aiStudyRecommendations: "AI Study Recommendations",
      suggestionsCount: "{count} suggestions",
      suggestedLabel: "Suggested",
      currentLabel: "Current",
      addToCalendar: "Add to calendar",
      dismiss: "Dismiss",
      review: "Review",
      aiLabel: "AI",
      doneCount: "{count} Done",
      timeMinsSecs: "{m}m {s}s",
      timeSecs: "{s}s",
      thisTopic: "this topic",
      questionsStillLoading: "Questions are still loading. Please wait a moment and try again.",
      noReviewSessionsFoundForDay: "No review sessions found for this day.",
      questionsNotFound: "Questions not found in database.",
      failedStartReviewTryAgain: "Failed to start review. Please try again.",
      failedStartStudySessionTryAgain: "Failed to start study session. Please try again.",
      aiRecommendationAddedSuccess: "✅ AI recommendation added to your calendar!",
      failedAddRecommendationWithReason: "Failed to add recommendation to calendar:\n\n{reason}",
      eventTypeEvent: "Event",
      deleteEventConfirm: "Delete this {eventType}? This will also remove all linked study suggestions and reviews.",
      eventDeletedSuccess: "Event deleted successfully!",
      failedDeleteEventWithReason: "Failed to delete event: {reason}",
      mcqCount: "{count} MCQs",
      noQuestionsAvailableForTopicSubtopic: "No questions available for {topic}{subtopic}.",
      noQuestionsAvailableForSuggestion: "No questions available for {topic}{subtopic}.\n\nPlease check that your question database includes this topic.",

      start: "Start",
      loadFirst40: "Load first 40",
      loadMore: "Load more",
      clickLoadToPreviewQuestions: "Click \"Load first 40\" to preview and start.",
      srsOverdueDays: "Overdue {count} day(s)",
      studySessionPreviewTitle: "Study Session Preview",
      phaseLabel: "Phase",
      scheduledEvents: "Scheduled Events",
      legendQuiz: "Quiz",
      legendStudyPlan: "Study Plan",
      legendAiSuggestion: "AI Suggestion",

      weekdaySunShort: "Sun",
      weekdayMonShort: "Mon",
      weekdayTueShort: "Tue",
      weekdayWedShort: "Wed",
      weekdayThuShort: "Thu",
      weekdayFriShort: "Fri",
      weekdaySatShort: "Sat",

      eventType: "Event Type",
      eventTypeRequired: "Event Type *",
      majorExam: "Major Exam",
      majorExamDesc: "10-day study plan with scaled intensity",
      smallQuiz: "Small Quiz",
      smallQuizDesc: "3-day focused review plan",

      examQuizDate: "Exam/Quiz Date",
      dateInputPlaceholder: "MM/DD or YYYY/MM/DD (e.g., 12/25 or 2024/12/25)",
      dateQuickLabel: "Quick:",
      dateFullLabel: "Full:",
      invalidDateHelp: "Please enter a valid date:\n\n• MM/DD (uses current year)\n• YYYY/MM/DD (specific year)\n\nExamples: 12/25 or 2024/12/25",
      pastDateWarningConfirm: "Warning: This date is in the past.\n\nDo you want to continue anyway?",

      filterTopicsSubtopics: "Filter Topics & Subtopics",
      topicsCount: "Topics ({selected}/{total})",
      topicsCountFull: "{selected}/{total} topic{plural}",
      subtopicsCount: "Subtopics ({selected}/{total})",
      subtopicsCountFull: "{selected}/{total} subtopic{plural}",
      selectAllTopicsUpToTitle: "Select all topics up to and including \"{topic}\"",
      selectAllSubtopicsUpToTitle: "Select all subtopics up to and including \"{subtopic}\"",
      upToHint: "Click \"Up to\" to select all topics up to that item",
      subtopicsAutoFilterHint: "Subtopics auto-filter based on selected topics",
      selectTopicsToFilterSubtopics: "Select topics to filter subtopics",
      noSubtopicsAvailable: "No subtopics available",

      customTitle: "Custom Title",
      autoTitlePlaceholder: "Auto: {title}",
      comprehensiveExam: "Comprehensive Exam",
      comprehensiveQuiz: "Comprehensive Quiz",
      topicsExamTitle: "{topics}{ellipsis} Exam",
      topicsQuizTitle: "{topics}{ellipsis} Quiz",

      autoGeneratedStudyPlan: "Auto-Generated Study Plan",
      planMajor10to7Label: "10-7 days before:",
      planMajor10to7Desc: "10 MCQs/day (Warm-up)",
      planMajor6to4Label: "6-4 days before:",
      planMajor6to4Desc: "20 MCQs/day (Consolidation)",
      planMajor3to1Label: "3-1 days before:",
      planMajor3to1Desc: "40 MCQs/day (Sprint Intensity)",
      planSmall3Label: "3 days before:",
      planSmall3Desc: "5 MCQs (Initial Review)",
      planSmall2Label: "2 days before:",
      planSmall2Desc: "10 MCQs (Topic Focus)",
      planSmall1Label: "1 day before:",
      planSmall1Desc: "15 MCQs (Final Polish)",
      focusLabel: "Focus:",
      allTopics: "All Topics",
      topicCountLabel: "{count} topic",
      subtopicCountLabel: "{count} subtopic",

      creating: "Creating...",
      createEventAndStudyPlan: "Create Event & Study Plan",
      eventCreatedSuccess: "Event created successfully!",
      failedCreateEventWithReason: "Failed to create event:\n\n{reason}",

      pleaseFillRequiredFields: "Please fill in all required fields",
      automaticPrepSuggestionsWillBeGenerated: "Automatic prep suggestions will be generated",
      titleRequired: "Title *",
      titlePlaceholder: "e.g., Chemistry Midterm Exam",
      dateRequired: "Date *",
      topicRequired: "Topic *",
      topicPlaceholder: "e.g., Organic Chemistry",
      subtopicOptional: "Subtopic (Optional)",
      subtopicPlaceholder: "e.g., Reaction Mechanisms",
      automaticSuggestions: "Automatic Suggestions:",
      automaticSuggestionsMajor: "Study plan with 10/20/40 MCQs (10-7, 6-4, 3-1 days before)",
      automaticSuggestionsSmall: "Quick review with 5-15 MCQs (3-1 days before)",
      createEvent: "Create Event",
      clickToStartPractice: "Click to start practice →",
    },

    // Forum
    forum: {
      title: "The MCQ Forum",
      discuss: "Discuss",
      discussion: "Discussion",
      categoryGeneral: "General",
      categoryQuestion: "Question",
      categoryAnnouncement: "Announcement",
      addComment: "Add Comment",
      editComment: "Edit Comment",
      deleteComment: "Delete Comment",
      noComments: "No comments yet. Be the first to discuss!",
      noCommentsYet: "No comments yet",
      beFirstToShareThoughts: "Be the first to share your thoughts!",
      loading: "Loading discussion...",
      connectDiscuss: "Connect and discuss with other students",
      notifications: "Notifications",
      markAllRead: "Mark all read",
      deleteAll: "Delete all",
      deleteAllNotificationsTitle: "Delete all notifications?",
      deleteAllNotificationsBody: "This will permanently delete all notifications. This action cannot be undone.",
      deleteAllNotificationsConfirm: "Delete all notifications?",
      noNotificationsYet: "No notifications yet",
      postNotFound: "Post not found.",
      likedYourComment: "liked your comment",
      repliedToPost: "replied to your post",
      likedYourPost: "liked your post",
      likedYourReply: "liked your reply",
      repliedToComment: "replied to your comment",
      interactedWithContent: "interacted with your content",
      justNow: "Just now",
      mcqDiscussion: "MCQ Discussion",
      generalForum: "General Forum",
      searchQuestions: "Search questions, topics, DSE codes...",
      recent: "Recent",
      popular: "Popular",
      questionsWithDiscussions: "questions with discussions",
      noResultsFound: "No results found",
      noMcqDiscussions: "No MCQ discussions yet. Start one from any quiz!",
      comments: "comments",
      searchPosts: "Search posts...",
      all: "All",
      newPost: "New Post",
      noPosts: "No posts yet. Be the first!",
      createPost: "Create a Post",
      backToForum: "Back to forum",
      edited: "edited",
      save: "Save",
      cancel: "Cancel",
      replies: "Replies",
      writeReply: "Write a reply...",
      reply: "Reply",
      pleaseLoginReply: "Please log in to reply.",
      createNewPost: "Create New Post",
      category: "Category",
      title2: "Title",
      enterClearTitle: "Enter a clear, descriptive title",
      content: "Content",
      shareThoughts: "Share your thoughts, question, or announcement...",
      post: "Post",
      deletePost: "Delete this post?",
      deleteReply: "Delete this reply?",
      editExpired: "Edit window expired (15 min).",
      editWindowExpired: "Edit window expired",
      editExpiredLong: "Edit window has expired (15 minutes). You can no longer edit this comment.",
      editWindowLabel: "Edit window:",
      editLocked: "Edit locked",
      editIn: "Edit in {remaining}",
      confirmDeleteComment: "Are you sure you want to delete this comment?",
      failedDeleteComment: "Failed to delete comment",
      failedUpdateComment: "Failed to update comment",
      failedAddCommentWithReason: "Failed to add comment: {reason}",
      failedReplyWithReason: "Failed to reply: {reason}",
      pleaseLoginToLikeComments: "Please log in to like comments",
      pleaseLoginJoinDiscussion: "Please log in to join the discussion",
      shareYourThoughts: "Share your thoughts...",
      hideReplies: "Hide replies",
      commentsCount: "{count} Comments",
      timeAgoMinutes: "{count} min ago",
      timeAgoHours: "{count} hr ago",
      timeAgoDays: "{count} days ago",
      timeAgoMinutesShort: "{count}m",
      timeAgoHoursShort: "{count}h",
      timeAgoDaysShort: "{count}d",
    },
    
    // Mistake Notebook
    notebook: {
      // Main Navigation
      title: "Mistake Notebook",
      commandCenter: "Custom Mistake Review",
      mistakeDeck: "Mistake Deck",
      learningInsights: "Learning Insights",
      learningAnalytics: "Learning Analytics",
      archive: "Archive",
      masteryArchive: "Mastery Archive",
      questionsHidden: "Questions are hidden on this page. Start a quiz to view them.",

      filterInfoTitle: "About Topic/Subtopic filters",
      filterInfoBody: "Topic/Subtopic filters search across all of your mistake questions, not only the first 40 shown on screen. Use \"Load more\" to display more results.",
      close: "Close",
      
      activeFilters: "Active filters",
      clearAll: "Clear all",

      // Actions
      review: "Review Mistakes",
      practiceMistakes: "Practice Mistakes Only",
      practiceMistakesCount: "Practice {count} Mistake{plural}",
      practiceSelected: "Practice {count} Selected",
      cleared: "All mistakes cleared!",
      addedToNotebook: "Added to Mistake Notebook",
      removedFromNotebook: "Removed from Notebook",
      reviewMaster: "Review and master questions you got wrong",
      
      // Full Question Modal
      questionDetail: "Question Detail",
      question: "Question",
      options: "Options",
      viewFullQuestion: "View Full Question",
      viewFull: "View Full",
      attempts: "Attempts",
      masteryLevelLabel: "Mastery Level",
      lastAttemptedLabel: "Last Attempted",
      
      // Statistics
      totalMistakes: "Total Mistakes",
      topicsToFocus: "Topics to Focus",
      repeatedMistakes: "Repeated Mistakes",

      customReview: "Custom Review",
      customReviewSubtitle: "Configure your practice session",
      sessionPreview: "Session preview",
      willPractice: "Will practice",
      masteryBreakdown: "Breakdown",
      custom: "Custom",
      timerSettings: "Timer",
      
      // Configurator
      configurePractice: "Configure Practice Session",
      numberOfQuestions: "Questions",
      questionsLabel: "1. Number of Questions",
      questionsAvailable: "available",
      questionsAvailableFull: "questions available with current filters",
      timeRange: "Time Range",
      timeRangeLabel: "2. Time Range (when you made the mistake)",
      allTime: "All Time",
      lastMonth: "Last Month",
      lastWeek: "Last Week",
      default: "default",
      
      // Filters
      topics: "Topics",
      topicsLabel: "3. Topics (leave empty for all)",
      subtopics: "Subtopics",
      subtopicsFilteredNote: "(filtered by selected topics)",
      masteryLevel: "Mastery Level",
      srsPresence: "SRS",
      srsPresenceAll: "All",
      srsPresenceInSrs: "In SRS",
      srsPresenceNotInSrs: "Not in SRS",
      clearTopicFilter: "✕ Clear topic filter",
      clearSubtopicFilter: "Clear subtopic filter",
      clearMasteryFilter: "Clear mastery filter",
      filteredFrom: "Filtered from",
      clearSelection: "Clear Selection",
      
      // Mastery Status Labels
      masteryNotInSrs: "Not in SRS",
      masteryNew: "New",
      masteryDeveloping: "Developing",
      masteryProgressing: "Progressing",
      masteryNear: "Near-Mastery",
      masteryMastered: "Mastered",
      mastered: "Mastered",
      statusUnprocessed: "Unprocessed",
      statusInProgress: "In Progress",
      statusNearMastery: "Near Mastery",
      
      // Empty States
      allMistakes: "All Mistakes",
      noMistakesYet: "No mistakes yet!",
      keepPracticing: "Keep practicing. Wrong answers appear here.",
      startPracticing: "Start Practicing",
      noQuestionsFound: "No questions match your filters",
      tryAdjustFilters: "Try adjusting your filter settings",
      noArchivedYet: "No archived questions yet",
      archiveInstructions: "Archive has two types: Mastery (SRS) and Overdue (auto-cleanup)",
      archiveSubtabMastery: "Mastery",
      archiveSubtabOverdue: "Overdue",
      archiveSubtabCount: "Showing {count}",

      archiveMasteryHowTitle: "Mastery archive (SRS)",
      archiveMasteryHowBody: "A question enters Mastery archive when it reaches 5 successful SRS reviews. The schedule is: 1st correct → 1 day, 2nd correct → 6 days, then future intervals grow by interval × ease factor. If you answer wrong, the progress resets (repetition count back to 0) and it returns to 1-day review.",
      archiveOverdueHowTitle: "Overdue archive (auto-cleanup)",
      archiveOverdueHowBody: "If a question is due on its next review date but you do not review it for more than 14 days after that due date, it will be auto-archived to reduce noise. You can always restore it from here.",

      noMasteryArchives: "No mastery archives yet",
      noMasteryArchivesHint: "Keep reviewing with SRS until it graduates (5 successful reviews).",
      noOverdueArchives: "No overdue archives",
      noOverdueArchivesHint: "Overdue archives appear when a due review is ignored for 14+ days.",
      allCaughtUp: "All caught up!",
      
      // Question Details
      lastAttempt: "Last Attempt",
      missed: "Missed {count}×",
      yourAnswer: "Your Answer",
      correctAnswer: "Correct Answer",
      correct: "Correct",
      explanation: "Explanation",
      priority: "Priority",
      
      // How It Works
      howItWorks: "How it works",
      wrongAnswersAutoSaved: "Wrong answers are auto-saved here",
      useFilters: "Use filters to focus on specific topics or recent mistakes",
      practiceUntilMaster: "Practice until you master them!",
      clearAfterThreeCorrect: "✨ Questions automatically clear after 3 consecutive correct attempts!",
      
      // Loading States
      loadingMistakes: "Loading mistakes...",
      sessionLimited: "Session limited to {max} questions maximum.",
      
      // Topic Analysis
      topicBreakdown: "Topic Breakdown",
      hoverForDetails: "Hover over stats for details",
      weakTopics: "Weak Topics",
      focusTheseTopics: "Focus on these topics",
      repeatsByTopic: "Repeated Mistakes by Topic",
      needMorePractice: "Need more practice",
      improved: "Improved {count}",
      
      // Retention Dashboard
      retentionDashboard: "Retention Dashboard",
      addedThisWeek: "Added (7d)",
      masteredThisWeek: "Mastered (7d)",
      decayRate: "Decay Rate",
      decayImproving: "Improving",
      decayStable: "Stable",
      decayGrowing: "Growing",
      weakestSubtopics: "Weakest Subtopics",
      urgentReviews: "Urgent Reviews (by priority score)",
      
      // Priority Badge
      priorityScore: "Spaced Repetition Priority Score",
      
      // Metacognitive Tagging
      errorTypeLabel: "Error Type:",
      tagErrorType: "Tag Error Type",
      errorCategory: "Error Category",
      clearTag: "Clear tag",
      errorTypeMisread: "Misread Question",
      errorTypeConceptual: "Conceptual Gap",
      errorTypeCalculation: "Calculation Error",
      errorTypeCareless: "Careless Mistake",
      errorTypeVocab: "Vocabulary Gap",
      errorTypeDiagram: "Diagram Misread",
      errorMisread: "Misread Question",
      errorConceptual: "Conceptual Gap",
      errorCalculation: "Calculation Error",
      errorCareless: "Careless Mistake",
      errorVocabulary: "Vocabulary Gap",
      errorDiagram: "Diagram Misread",
      tagError: "Tag Error",
      
      // Extra Notes
      spacedRepetitionNote: "Cards sorted by Spaced Repetition priority — highest urgency first.",
      metacognitiveNote: "Tag each mistake with an Error Category to track your patterns.",
      
      // Learning Analytics Dashboard
      mistakeClearingActivity: "SRS Mistake Clearing Activity",
      errorDensityByTopic: "Error Density by Topic",
      improvementTrend: "SRS Improvement Trend (14 days)",
      srsTrendTitle: "SRS Improvement Trend (14 days)",
      srsTrendSubtitle: "What this chart means, and how to read it.",
      srsTrendPurposeTitle: "Purpose",
      srsTrendPurposeBody: "This chart helps you see whether you are still making first-time mistakes, building up practice, or pushing questions towards mastery.",
      srsTrendMechanicsTitle: "How it works",
      srsTrendMechanicsBody: "Each day, your reviews are grouped into stages. The numbers can go up or down day by day because they show activity for that day, not your total history.",
      srsTrendBucketsTitle: "Stage meanings",
      srsTrendNewDesc: "You got the question wrong on your very first SRS review of it.",
      srsTrendDevelopingDesc: "You are training the question. This includes questions you got correct on the first review, and questions that dropped back after a wrong answer.",
      srsTrendNearDesc: "You have answered the question correctly multiple times, so the review interval becomes longer.",
      srsTrendMasteredDesc: "You reached the graduation requirement (for example, 5 successful reviews).",
      srsTrendHowToReadTitle: "How to read the chart",
      srsTrendHowToReadBody: "Higher bars mean you did more reviews in that stage on that day. If a stage drops to 0 today, it usually means you had fewer reviews in that stage today — it does not mean you lost progress.",
      srsTrendInfoAria: "Open SRS improvement trend info",
      srsClearingInfoAria: "Open SRS clearing activity info",
      srsClearingTitle: "SRS Mistake Clearing Activity",
      srsClearingSubtitle: "What this heatmap measures, and why some days can be 0.",
      srsClearingPurposeTitle: "Purpose",
      srsClearingPurposeBody: "This heatmap helps you track consistency. It shows how many SRS reviews you cleared correctly each day.",
      srsClearingMechanicsTitle: "How it works",
      srsClearingMechanicsBody: "A day becomes darker when you cleared more reviews correctly on that day. A day showing 0 usually means you did not clear any reviews correctly that day.",
      selectedCount: "{count} selected",
      weekdaySunShort: "S",
      weekdayMonShort: "M",
      weekdayTueShort: "T",
      weekdayWedShort: "W",
      weekdayThuShort: "T",
      weekdayFriShort: "F",
      weekdaySatShort: "S",
      activityTooltipCleared: "{date}: {count} cleared",
      questionDiagramAlt: "Question diagram",
      clickTopicToFilter: "Click a topic to filter →",
      clickTopicsToFilter: "Click topics to filter (multi-select)",
      less: "Less",
      more: "More",
      
      // AI Daily Mission
      aiDailyMission: "AI Daily Mission",
      aiDailyMissionNote: "Smart AI selects 10 questions with interleaved practice to maximize retention.",
      needMoreQuestions: "Need 10+ mistakes (have {count})",
      interleavedPractice: "10 Questions • Interleaved Practice",
      
      // Timer Settings
      timerEnabled: "Show Timer",
      timedMode: "Timed Mode",
      
      // View Modes
      listView: "List View",
      kanbanView: "Kanban View",
      selectAll: "Select All",
      
      // Archive
      mastered: "Mastered",
      masteredOn: "Mastered {date}",
      archivedAt: "Archived at",
      
      // Filter Pills
      topicFilter: "Topic: {topic}",
    },
    
    // History
    history: {
      title: "Practice History",
      clickToSeeAnalysis: "Click any attempt to see the full analysis",
      viewingAttemptFromCalendar: "Viewing attempt from calendar",
      totalAttempts: "Total Attempts",
      averageScore: "Average Score",
      bestScore: "Best Score",
      totalTime: "Total Time",
      filtersAndSorting: "Filters & Sorting",
      timePeriod: "Time Period",
      allTime: "All Time",
      lastMonth: "Last Month",
      lastWeek: "Last Week",
      sortBy: "Sort By",
      recent: "Recent",
      score: "Score",
      time: "Time",
      yourAttempts: "Your Attempts",
      clickViewAnalysis: "Click to view full analysis",
      refresh: "Refresh",
      noAttemptsFound: "No attempts found",
      tryChangingFilter: "Try changing the filter period",
      startPracticingHistory: "Start practicing to see your history!",
      takeFirstQuiz: "Take Your First Quiz",
      correct: "correct",
      loadingHistory: "Loading your history...",
      timeHrsMins: "{h}h {m}m",
      timeMinsSecs: "{m}m {s}s",
      timeSecs: "{s}s",
    },

    firebaseTest: {
      title: "Firebase Connection Test",
      subtitle: "Diagnose data saving issues",
      runFirebaseTests: "Run Firebase Tests",
      runningTests: "Running Tests...",
      testResults: "Test Results",
      howToInterpretResults: "How to interpret results:",
      authLabel: "Auth",
      profileLabel: "Profile",
      saveAttemptLabel: "Save Attempt",
      fetchAttemptsLabel: "Fetch Attempts",
      leaderboardLabel: "Leaderboard",
      authInterpret: "Should show your email if logged in",
      profileInterpret: "Should load your user data from Firestore",
      saveAttemptInterpret: "Should successfully save a test quiz result",
      fetchAttemptsInterpret: "Should retrieve your quiz history",
      leaderboardInterpret: "Should load ranking data",
      commonIssues: "Common Issues:",
      issueNotAuthenticatedTitle: "Not authenticated:",
      issueNotAuthenticatedDesc: "Make sure you're logged in",
      issueFailedSaveFetchTitle: "Failed to save/fetch:",
      issueFailedSaveFetchDesc: "Check Firebase Firestore rules",
      issuePermissionDeniedTitle: "Permission denied:",
      issuePermissionDeniedDesc: "Update Firestore security rules to allow read/write",
      recommendedFirestoreRules: "Recommended Firestore Rules:",
      authenticatedAs: "Authenticated as {email}",
      notAuthenticated: "Not authenticated",
      profileLoadedWithAttempts: "Profile loaded ({count} attempts)",
      profileNotFound: "Profile not found",
      testAttemptSavedWithId: "Test attempt saved! ID: {id}",
      failedSaveAttemptWithReason: "Failed to save attempt: {reason}",
      skippedNotAuthenticated: "Skipped - not authenticated",
      fetchedAttemptsCount: "✅ Fetched {count} attempts",
      failedFetchAttemptsWithReason: "❌ Failed to fetch attempts: {reason}",
      leaderboardLoadedUsersCount: "✅ Leaderboard loaded ({count} users)",
      failedLoadLeaderboardWithReason: "❌ Failed to load leaderboard: {reason}",
    },

    // Common
    common: {
      loading: "Loading...",
      error: "Error",
      success: "Success",
      backToDashboard: "Back to Dashboard",
      confirm: "Confirm",
      cancel: "Cancel",
      clear: "Clear",
      on: "On",
      off: "Off",
      save: "Save",
      delete: "Delete",
      edit: "Edit",
      close: "Close",
      retry: "Retry",
      backToTopics: "Back to Topics",
      optional: "Optional",
      anonymous: "Anonymous",
      someone: "Someone",
      ninePlus: "9+",
      notAvailable: "N/A",
      ellipsis: "...",
      avatar: "Avatar",
      selectAll: "Select All",
      all: "All",
    },

    // Authentication
    auth: {
      login: "Login",
      register: "Register",
      email: "Email Address",
      password: "Password",
      confirmPassword: "Confirm Password",
      fullName: "Full Name",
      createAccount: "Create Account",
      alreadyHaveAccount: "Already have an account?",
      dontHaveAccount: "Don't have an account?",
      loginHere: "Login here",
      registerHere: "Register here",
      welcomeBack: "Welcome Back",
      enterCredentials: "Enter your credentials to access your account",
      signingIn: "Signing in...",
      signIn: "Sign In",
      createAccountNow: "Create one now",
      secureLogin: "Secure login powered by Firebase Authentication",
      signInToContinue: "Sign in to continue",
      emailPlaceholder: "your.email@example.com",
      passwordPlaceholder: "••••••••",
      fullNamePlaceholder: "Chem Leung",
      noAccountFound: "No account found with this email.",
      incorrectPassword: "Incorrect password.",
      invalidEmail: "Invalid email address.",
      failedLogin: "Failed to log in. Please check your credentials.",
      joinCommunity: "Join our chemistry learning community",
      creatingAccount: "Creating account...",
      passwordsNoMatch: "Passwords do not match",
      passwordMinLength: "Password must be at least 6 characters",
      enterFullName: "Please enter your full name",
      emailAlreadyInUse: "An account with this email already exists.",
      weakPassword: "Password is too weak. Use at least 6 characters.",
      failedCreateAccount: "Failed to create account. Please try again.",
      minimumCharacters: "Minimum 6 characters",
      secureRegistration: "Secure registration powered by Firebase Authentication",
      switchToChinese: "Switch to Traditional Chinese",
      switchToEnglish: "Switch to English",
      languageNameChinese: "繁體中文",
      languageNameEnglish: "English",
    },

    // ChemStore
    store: {
      title: "ChemStore",
      subtitle: "Unlock exclusive items with your diamonds",
      yourBalance: "Your Balance",
      profilePics: "Profile Pics",
      badges: "Badges",
      themes: "Themes",
      equipped: "Equipped",
      equip: "Equip",
      buy: "Buy",
      claim: "Claim",
      locked: "Locked",
      buying: "Buying...",
      comingSoon: "Coming soon! ",
      howToEarnTokens: "How to Earn Diamonds",
      correctAnswers: "Correct answers:",
      correctAnswersTokens: "1 diamond for every 2 correct answers.",
      quizBonus: "Quiz bonus (10+ questions):",
      quizBonusTokens: "100% = 20 diamonds, 80%+ = 15 diamonds, 50%+ = 10 diamonds",
      dailyReward: "Daily reward:",
      dailyRewardTokens: "5 diamonds per day",
      weeklyLeaderboard: "Weekly leaderboard:",
      weeklyLeaderboardTokens: "1st place = 30 diamonds, 2nd = 27, 3rd = 24, ...",
      millionaireGame: "Millionaire game:",
      millionaireGameTokens: "Reach higher questions to earn more diamonds (1-100 diamonds based on level)",
      notEnoughTokens: "Not enough diamonds! ",
      purchased: "Purchased {name}! ",
      purchaseFailed: "Purchase failed",
      failedToEquip: "Failed to equip",
      pleaseTryAgain: "Please try again.",
      failedToEquipItem: "Failed to equip item",
    },

    // Practice Mode Selection
    practiceMode: {
      updateYourTopics: "Update Your Topics",
      learnedUpTo: "Learned Up To:",
      exceptions: "Exceptions (Not Learned):",
      saveChanges: "Save Changes",
      updating: "Updating...",
      topicsUpdated: "Topics updated successfully!",
      failedUpdate: "Failed to update topics",
      configureCustomSession: "Configure Custom Session",
      questionsLoaded: "{count} Questions Loaded",
      back: "Back",
      selectTopics: "1. Select Topics (Multi-choice)",
      selectAllTopics: "Select All Topics",
      allSelected: "All Selected",
      lockedTopicsNotLearned: "Locked topics not yet learned. Update in Profile or click button above.",
      focusSubtopics: "2. Focus on Subtopics (Optional)",
      sessionLength: "3. Session Length",
      generateExam: "GENERATE EXAM",
      startPractice: "Start Practice",
      noQuestionsFound: "No questions found for this selection.",
      tryBroaderFilters: "Try broader filters!",
    },
  },
  
  zh: {
    // 品牌
    appName: "ChemLeung HKDSE MCQ 練習平台",
    tagline: "HKDSE 化學練習",
    
    // 導航
    nav: {
      dashboard: "總覧",
      practice: "練習",
      leaderboard: "排行榜",
      history: "歷史記錄",
      profile: "個人資料",
      logout: "登出",
    },

    header: {
      tokens: "鑽石",
      myHistory: "我的歷史",
      tokenHistory: "鑽石歷史",
      logoutWarning: "您將登出帳戶。任何未儲存的進度將會遺失。",
      confirmLogoutInQuiz: "確定要登出嗎？\n\n⚠️ 您正在進行測驗，進度將會丟失！",
      confirmLeaveQuiz: "確定要離開測驗嗎？\n\n⚠️ 您目前的進度將會丟失！",
    },

    // 總覧
    dashboard: {
      welcomeBack: "歡迎回來",
      totalAttempts: "總測驗次數",
      overallAccuracy: "整體準確率",
      questionsSolved: "已完成題數",
      correctAnswers: "答對題數",
      studyStreak: "學習連續天數",
      days: "日",
      startNewQuiz: "開始新測驗",
      viewLeaderboard: "查看排行榜",
      recentAttempts: "最近測驗",
      noAttempts: "暫時沒有紀錄！",
      takeFirstQuiz: "開始你的第一個測驗",
      browseForm: "瀏覽論壇",
      mistakeNotebook: "錯題本",

      // Learning Insights
      learningInsights: "學習洞察",
      viewAll: "查看全部",
      noLearningData: "暫時沒有學習數據",
      startLearningJourney: "開始你的學習之旅",
      startPracticing: "開始練習以查看洞察",
      availableFeatures: "可用功能",
      learningFeatures: "學習功能",
      exploreLearningNotebook: "探索學習筆記本",
      openLearningNotebook: "打開學習筆記本",

      // Feature titles and descriptions
      learningAnalytics: "學習分析",
      learningAnalyticsDesc: "追蹤進度與表現趨勢",
      mistakeDeckWithSRS: "錯題卡組（SRS）",
      mistakeDeckWithSRSDesc: "用間隔重複提升記憶效果",
      masteryArchiveSystem: "掌握度歸檔系統",
      masteryArchiveSystemDesc: "整理已掌握的主題",
      progressTrackingCharts: "進度追蹤與圖表",
      progressTrackingChartsDesc: "用視覺化方式掌握學習狀況",

      // Stats
      totalMistakes: "錯題總數",
      topics: "主題",
      repeated: "重複",
      topTopicsToFocus: "最需要加強的主題",
      mistakes: "錯題",
      density: "密度",
      dailyReward: "每日獎勵",
      claiming: "領取中...",
      logout: "登出",
      confirmLogout: "確認登出",
      areYouSureLogout: "確定要登出嗎？",
      needSignInAgain: "登出後你需要重新登入才能繼續練習。",
      cancel: "取消",
      errorLoadingAttempts: "載入紀錄失敗",
      retry: "重試",
      clickRowFullAnalysis: "點擊任何一列查看完整分析",
      refresh: "重新整理",
      noDataYet: "暫無資料",
      completeQuizSeeResults: "完成一次測驗後在此查看結果",
      timeSpent: "花費時間",
      loadingDashboard: "正在載入總覧...",

      howThisWorks: "如何運作",
      priorityReviewTitle: "優先重溫",
      top3UrgentMistakes: "最急需重溫的 3 條錯題（ISRS 演算法）",
      priorityReviewEmpty: "尚未追蹤到錯題。完成測驗並記錄錯題後，系統會提供個人化重溫建議！",
      priorityReviewMechanismTitle: "優先重溫機制",
      priorityReviewMechanismDesc: "此面板會使用 ISRS 優先分數，顯示最需要立即修正的前 3 條錯題。",
      whatIncreasesPriorityTitle: "什麼會提高優先度",
      whatIncreasesPriorityDesc: "最近答錯、更常重複錯、以及你近期學過的主題。",
      whatQuickFixDoesTitle: "「快速修正」會做什麼",
      whatQuickFixDoesDesc: "立即開始針對該題的練習，幫你快速修正弱點。",
      priorityCritical: "非常高",
      priorityHigh: "高",
      priorityMedium: "中",
      priorityLow: "低",
      priorityLabel: "{level} 優先度",
      questionTextNotAvailable: "題目內容暫不可用",
      attempts: "次數",
      correct: "正確",
      quickFix: "快速修正",
      viewFullMistakeNotebook: "查看完整錯題本",

      masteryHealthBarTitle: "掌握度健康條",
      ruleOf3Subtitle: "基於 Rule of 3 系統",
      masteryHealthBarMechanismTitle: "掌握度健康條機制",
      masteryMechanismDesc: "主題會根據正確次數（Rule of 3）在 3 個狀態之間變化。",
      masteryNewTitle: "未開始",
      masteryNewDesc: "尚未嘗試。",
      masteryImprovingTitle: "進步中",
      masteryImprovingDesc: "1–2 次答對。",
      masteryMasteredTitle: "已掌握",
      masteryMasteredDesc: "3+ 次答對。",
      masteryBarExplainer: "健康條會以這 3 個分類顯示你的課程覆蓋度。",
      syllabusCoverage: "課程覆蓋度",
      topicsTrackedCount: "已追蹤 {count} 個主題",
      unseenTooltip: "{pct}% 未開始（{count} 個主題）",
      improvingTooltip: "{pct}% 進步中（{count} 個主題）",
      masteredTooltip: "{pct}% 已掌握（{count} 個主題）",

      quickStatsTitle: "快速統計",
      quickStatsMechanismTitle: "快速統計機制",
      quickStatsMechanismDesc: "此區塊快速總結你的學習動能與進度。",
      quickStatsStudyStreakTitle: "連續學習",
      quickStatsStudyStreakDesc: "根據近期活動計算連續學習天數。",
      quickStatsTopicsMasteredTitle: "已掌握主題",
      quickStatsTopicsMasteredDesc: "已達到掌握門檻的主題數量。",
      quickStatsInProgressTitle: "進行中",
      quickStatsInProgressDesc: "已開始但尚未掌握的主題（繼續練習即可提升）。",

      quizSessionsCount: "{count} 次測驗",
      correctOutOfTotal: "{correct}/{total} 正確",
      clickAnyAttempt: "點擊任何紀錄",
      toSeeDetailedAnalysis: "查看詳細分析與洞察",

      priorityReviewAiStudySuggestionTitle: "優先重溫：AI 學習建議",
      aiStudySuggestionsEmpty: "暫時沒有 AI 建議。繼續練習以解鎖個人化推薦。",
      aiSuggestionsMechanismTitle: "AI 學習建議",
      aiSuggestionsMechanismDesc: "這些建議會根據你近期在主題／副主題的表現產生。接受後會把建議學習時段加入你的日曆。",
      aiStudySuggestionsMechanismDescLong: "AI 會分析你在主題／副主題的準確率趨勢，並建議需要加強的範圍。這能幫助你更有效率地安排學習。",

      srsReviewTitle: "SRS 重溫",
      srsReviewSubtitle: "把弱點變成強項",
      srsReviewDesc: "用間隔重複把錯題練到熟。",
      srsReviewMechanismTitle: "SRS 重溫機制",
      srsReviewMechanismDesc: "SRS（間隔重複系統）會在最佳時間安排重溫：第 1 次 1 天後、第 2 次 6 天後，之後間隔 × 難度係數（預設 2.5）。答錯會重置進度。完成 5 次成功重溫後，卡片會畢業到掌握度歸檔。",
      srsReviewMechanismDescLong: "SRS（間隔重複系統）會在最佳時間安排重溫：第 1 次 1 天後、第 2 次 6 天後，之後間隔 × 難度係數（預設 2.5）。答錯會重置進度。完成 5 次成功重溫後，卡片會畢業到掌握度歸檔。這能幫助你鞏固記憶並減少遺忘。",

      aiHowGeneratesTitle: "AI 如何產生建議",
      aiHowGeneratesDesc: "• 分析你在主題／副主題的準確率趨勢\n• 找出弱點（低於 60% 準確率）\n• 優先處理你近期最常錯的主題\n• 建議合適的練習題數",
      aiPriorityLevelsTitle: "優先級別",
    },

    common: {
      loading: "載入中...",
      error: "錯誤",
      success: "成功",
      backToDashboard: "返回主頁",
      confirm: "確認",
      cancel: "取消",
      clear: "清除",
      on: "開",
      off: "關",
      save: "儲存",
      delete: "刪除",
      edit: "編輯",
      close: "關閉",
      retry: "重試",
      backToTopics: "返回題目選擇",
      optional: "選填",
      anonymous: "匿名",
      someone: "某人",
      ninePlus: "9+",
      notAvailable: "不適用",
      ellipsis: "...",
      avatar: "頭像",
      selectAll: "全選",
      all: "全部",
    },

    srs: {
      title: "Spaced Repetition Review",
      failedLoadDueCardsTryAgain: "無法載入待重溫題目，請再試一次。",
      loadingDueCards: "載入中...",
      pleaseSelectAtLeastOne: "請至少選擇一條題目進行重溫。",
      questionsStillLoading: "題庫仍在載入中，請稍等再試。",

      questionsNeedReviewCount: "{count} 題需要重溫",
      questionsNeedReviewShownOutOfTotal: "顯示 {shown}/{total} 條到期題目",
      reviewMode: "重溫模式",
      quickReview: "快速重溫",
      aiSelectsRandomQuestions: "AI 隨機選題",
      defaultBadge: "✓ 預設",
      singleQuestion: "單題重溫",
      reviewOneMistake: "重溫一題",
      customBatch: "自訂批次",
      selectSpecificCards: "選擇指定卡片",
      numberOfQuestions: "題數",
      nQuestions: "{count} 題",
      allCount: "全部（{count}）",

      timerSettings: "計時設定",
      enableTimer: "啟用計時",
      showTimer: "顯示計時",
      timedMode75sPerQuestion: "限時模式（每題 75 秒）",
      mustAnswerWithin75SecondsPerQuestion: "每題必須在 75 秒內作答",
      timerTracksSpeedNoLimit: "只記錄作答時間，不設限時",
      noTimerTracking: "不記錄時間",
      timedModeSummary75: "限時：每題 75 秒",
      timerTrackingEnabled: "已啟用計時記錄",
      noTimer: "不計時",

      selectCardsToReview: "選擇要重溫的卡片",
      selectedCountOutOfTotal: "已選 {selected}／{total}",
      deselectAll: "取消全選",
      selectAll: "全選",
      dueLabel: "到期",
      noTopic: "無主題",
      noDueCardsMatchFilters: "沒有符合篩選條件的待重溫題目",
      questionIdLabel: "題目 ID",
      questionIdHelp: "對應題庫中的 MCQ ID",
      intervalLabel: "間隔",
      attemptLabel: "次數",
      easeLabel: "難度係數",

      startQuickReviewCount: "開始快速重溫（{count} 題）",
      startSingleReview: "開始單題重溫",
      startBatchReviewCount: "開始批次重溫（{count} 題）",

      overdueReviewsNotShown: "你有 {count} 個逾期重溫（未在此顯示）",
    },

    practiceModeLegend: {
      regular: "一般模式",
      mistakeReview: "錯題重溫",
      gameMode: "遊戲模式",
      timedShort: "限時",
      untimedShort: "不限時",
      customShort: "自訂",
      aiDailyShort: "AI 每日",
      srsShort: "SRS",
      millionaireShort: "百萬富翁",
    },

    practiceModeCarousel: {
      headerTitle: "選擇練習模式",
      headerSubtitle: "選擇一個模式開始你的學習之旅",
      previousMode: "上一個模式",
      nextMode: "下一個模式",
      startSession: "開始練習",
      clickToSelect: "點擊選擇",
      selectedLabel: "已選擇：{mode}",
      selectModeAria: "選擇 {mode}",

      timedTitle: "限時模式",
      timedSubtitle: "每題 1.25 分鐘",
      timedDesc: "最適合考試模擬",
      marathonTitle: "不限時模式",
      marathonSubtitle: "無時間壓力",
      marathonDesc: "慢慢做，專注理解",
      aiDailyTitle: "AI 每日重溫",
      aiDailySubtitle: "每日重點練習",
      aiDailyDesc: "AI 從你近期弱點中挑選 10 題。",
      aiDailyInfoTitle: "AI 每日重溫如何運作",
      aiDailyInfoBody: "AI 每日重溫會從你過往答錯的題目中挑選 10 題，優先安排近期或重複出錯的題目，並盡量平衡不同主題。",
      mistakeReviewTitle: "錯題重溫",
      mistakeReviewSubtitle: "針對弱點",
      mistakeReviewDesc: "練到完全掌握",
      srsReviewTitle: "SRS 重溫",
      srsReviewSubtitle: "間隔重溫",
      srsReviewDesc: "重溫到期題目，加強記憶。",
      customTitle: "自訂練習",
      customSubtitle: "由你決定",
      customDesc: "選擇主題與設定",

      millionaireTitle: "百萬富翁",
      millionaireSubtitle: "15 題階梯",
      millionaireDesc: "一題答錯即結束。答對越多題可獲得更多鑽石。",
    },

    millionaire: {
      modeName: "Millionaire",
      questionLabel: "題目",
      tokensUnit: "鑽石",
      tokenLadder: "鑽石階梯",
      safetyNet: "安全網",
      cleared: "已通關",
      now: "目前",
      amountTokens: "{count} 鑽石",

      lifelines: {
        aiTips: "AI 提示",
        fiftyFifty: "50:50",
        chemLeung: "ChemLeung",
      },

      rewardIfClear: "答對可得",
      currentBank: "目前累積",
      lockIn: "鎖定答案",
      quit: "退出",

      periodicTableOfElements: "元素週期表",
      periodicTable: "元素週期表",
      periodicTableAlt: "元素週期表",
      close: "關閉",
      details: "詳情",
      cashOutToSavePrefix: "提取獎金以保留你目前累積的",
      cashOutToSaveSuffix: "，",

      overlays: {
        finalDecision: "最後決定",
        confirmQuit: "確認退出",
        cashOutToSavePrefix: "提取獎金以保留你目前累積的",
        cashOutToSaveSuffix: "，",
        orStayContinue: "或繼續挑戰本回合。",
        cashOut: "提取獎金",
        stay: "留低",

        safeHaven: "安全點",
        safetyNetReached: "已達到安全網",
        guaranteedPrefix: "你的",
        guaranteedSuffix: "已被保證。",
        guaranteed: "你的 {amount} {unit} 已被保證。",
        safeHavenAt: "安全點：第{level}題",
        fireRoundWarning: "火焰回合來襲！接下來5題將是計時題，充滿火焰效果！",
        finalSafetyNet: "最終安全網！如果繼續，你將保證獲得60鑽石！",
        continue: "繼續",

        decision: "決定",
        correct: "正確！",
        clearedCurrentReward: "你已答對第{level}題。目前獎勵：",
        nextQuestion: "下一題",
      },

      gameOver: {
        finalResult: "最終結果",
        gameOver: "遊戲結束",
        finalRewardAria: "最終獎勵",
        cashOutConfirmed: "已確認提取獎金",
        perfectRun: "完美通關",
        timeUp: "時間到！",
        betterLuck: "下次再接再厲",
        questionsAnswered: "已作答題數",
        outOf: "共",
        playAgain: "再玩一次",
        exitToHome: "返回主頁",
      },

      probability: {
        title: "機率分析",
        subtitle: "AI 驅動答案分佈",
        basedOn: "根據分析結果，以下為各選項機率分佈：",
        optionLabel: "選項 {option}",
        warning: "⚠️ 這是機率估計，並非保證。請以你的知識作答！",
        gotIt: "明白！",
      },

      chemLeung: {
        expert: "化學專家",
        analyzing: "ChemLeung 正在分析題目...",
        defaultAnalysis: "以下是我對這題的專業分析...",
        remember: "記住：這只是建議，最終決定由你作出！",
        thanks: "多謝 ChemLeung！",
      },

      errors: {
        startFailed: "無法開始 Millionaire 模式",
        tokenUpdateFailed: "更新鑽石餘額失敗",
      },
    },
    
    // 練習模式
    practice: {
      selectMode: "選擇練習模式",
      timed: "限時練習",
      timedDesc: "與時間競賽 - {minutes} 分鐘",
      marathon: "馬拉松模式",
      marathonDesc: "無限時間 - 追蹤您的進度",
      custom: "自定義練習",
      customDesc: "選擇主題和題目數量",
      startPractice: "開始練習",
      selectPracticeMode: "選擇練習模式",
      chooseHowPractice: "選擇您的練習方式",
      perQuestion: "分鐘每題",
      perfectForExam: "最適合考試模擬，帶有倒數計時器。",
      takeYourTime: "慢慢來。我們會記錄時間但沒有壓力！",
      chooseSpecificTopics: "選擇特定主題、子主題和題數。",
      questions: "題數：",
      configure: "設定",
      quizSettingsTitle: "測驗設定",
      yourAvailableTopics: "您可用的主題",
      more: "更多",
      noTopicsConfigured: "尚未設定主題！",
      pleaseSetTopics: "請在個人資料設定中設定您已學習的主題。",
      goToProfile: "前往個人資料",
      updateTopics: "更新主題",
      mistakesToSrsTitle: "錯題加入 SRS",
      mistakesToSrsAlways: "總是",
      mistakesToSrsNever: "永不",
      mistakesToSrsAsk: "詢問",
    },
    
    // 測驗介面
    quiz: {
      question: "題目",
      questionPrefix: "第",
      of: "共",
      flagQuestion: "標記題目",
      unflagQuestion: "取消標記",
      periodicTable: "元素週期表",
      periodicTableAlt: "元素週期表",
      overview: "總覽",
      previous: "上一題",
      next: "下一題",
      submit: "提交",
      answered: "已答",
      flagged: "已標記",
      skipped: "跳過",
      timeRemaining: "剩餘時間",
      sessionTime: "練習時間",
      totalTime: "總時間",
      initializingQuiz: "初始化測驗中...",
      type: "輸入",
      toSelect: "選擇",
      flag: "標記",
      tools: "工具",
      backToTopics: "返回主題",
      periodicTableOfElements: "元素週期表",
      time: "時間",
      thisQuestion: "本題時間：",
      questionOverview: "題目概覽",
      tip: "提示：",
      press: "按",
      pleaseAnswerAll: "請在提交前回答所有問題。",
      finishSubmit: "完成並提交",
      confirmBackToTopics: "確定要返回主題選擇嗎？\n\n⚠️ 您的所有進度將會丟失！",
      enableTimer: "啟用計時器",
      trackTimeSpent: "追蹤每題用時",
      showTimer: "顯示計時器",
      countdown: "倒數計時",
      timedMode: "限時模式",
      countdownTimer: "倒數計時並設時限",
      timeUp: "時間到！您的測驗將立即提交。",
    },
    
    // 成績
    results: {
      yourPerformance: "您的表現",
      totalTime: "總時間",
      averagePerQuestion: "每題平均時間",
      strengths: "優勢領域",
      needsFocus: "需要加強",
      detailedReview: "詳細檢討",
      yourAnswer: "您的答案",
      correctAnswer: "正確答案",
      explanation: "解釋",
      shareReport: "分享成績單",
      addToNotebook: "加入錯題簿",
      startNewSession: "開始新練習",
      savingToProfile: "保存至您的個人資料...",
      savedToProfile: "已保存至您的個人資料！",
      reviewsSaved: "已保存重溫記錄！",
      addMistakesToSrsTitle: "將錯題加入 SRS？",
      addMistakesToSrsBody: "我們可以把你答錯的題目加入 SRS（間隔重溫），方便之後重溫。",
      addToSrs: "加入 SRS",
      addingToSrs: "加入中...",
      addedToSrs: "已加入 SRS！",
      failedAddToSrs: "加入 SRS 失敗。請再試一次。",
      saveFailed: "保存失敗",
      continueAnyway: "仍然繼續",
      resultsSavingLeaveConfirm: "您的測驗結果仍在保存中。確定要離開嗎？",
      resultsMayNotBeSavedLeaveConfirm: "您的結果可能尚未完全保存。確定要離開嗎？",
      resultsNotSavedContinueAnywayConfirm: "您的結果未能保存。仍要繼續嗎？",
    },

    report: {
      shareReportCard: "分享成績單",
      downloadPngTitle: "下載為 PNG 圖片",
      downloadPdfTitle: "下載為 PDF",
      image: "圖片",
      pdf: "PDF",
      fileNamePrefix: "ChemLeung-Report",
      website: "www.chemleung.com",
      dismiss: "關閉",
      hkDsePracticeReport: "HKDSE 化學練習報告",
      studentName: "學生姓名",
      student: "學生",
      topicsCovered: "涵蓋主題",
      topicsUnit: "個主題",
      outOf: "/",
      correctLabel: "正確",
      correct: "正確",
      incorrect: "錯誤",
      timeUsed: "用時",
      timeHrsMins: "{h}小時 {m}分鐘",
      timeMinsSecs: "{m}分鐘 {s}秒",
      topicBreakdown: "主題分析",
      generatedBy: "由 ChemLeung HKDSE MCQ 練習平台生成",
      generating: "生成報告中...",
      mayTakeSeconds: "這可能需要幾秒鐘",
      reportNotReady: "報告未準備好。請重試。",
      failedCreateImage: "無法創建圖片",
      failedExportImageTryPdf: "匯出圖片失敗。請嘗試 PDF 匯出。",
      failedExportPdfTryImage: "匯出 PDF 失敗。請嘗試圖片匯出。",
      na: "不適用",
    },

    firebaseTest: {
      title: "Firebase 連線測試",
      subtitle: "診斷資料保存問題",
      runFirebaseTests: "執行 Firebase 測試",
      runningTests: "測試中...",
      testResults: "測試結果",
      howToInterpretResults: "💡 如何理解結果：",
      authLabel: "驗證",
      profileLabel: "個人資料",
      saveAttemptLabel: "保存記錄",
      fetchAttemptsLabel: "讀取記錄",
      leaderboardLabel: "排行榜",
      authInterpret: "若已登入，應顯示您的電郵",
      profileInterpret: "應能從 Firestore 載入您的用戶資料",
      saveAttemptInterpret: "應能成功保存一個測試測驗結果",
      fetchAttemptsInterpret: "應能讀取您的測驗歷史",
      leaderboardInterpret: "應能載入排名資料",
      commonIssues: "常見問題：",
      issueNotAuthenticatedTitle: "未登入：",
      issueNotAuthenticatedDesc: "請確認您已登入",
      issueFailedSaveFetchTitle: "保存/讀取失敗：",
      issueFailedSaveFetchDesc: "請檢查 Firebase Firestore 規則",
      issuePermissionDeniedTitle: "權限不足：",
      issuePermissionDeniedDesc: "更新 Firestore 安全規則以允許讀寫",
      recommendedFirestoreRules: "建議 Firestore 規則：",
      authenticatedAs: "已登入為 {email}",
      notAuthenticated: "未登入",
      profileLoadedWithAttempts: "已載入個人資料（{count} 次記錄）",
      profileNotFound: "找不到個人資料",
      testAttemptSavedWithId: "✅ 已保存測試記錄！ID：{id}",
      failedSaveAttemptWithReason: "❌ 保存記錄失敗：{reason}",
      skippedNotAuthenticated: "⚠️ 已跳過（未登入）",
      fetchedAttemptsCount: "✅ 已讀取 {count} 次記錄",
      failedFetchAttemptsWithReason: "❌ 讀取記錄失敗：{reason}",
      leaderboardLoadedUsersCount: "✅ 已載入排行榜（{count} 位用戶）",
      failedLoadLeaderboardWithReason: "❌ 載入排行榜失敗：{reason}",
    },
    
    // 認證
    auth: {
      login: "登入",
      register: "註冊",
      email: "電郵地址",
      password: "密碼",
      confirmPassword: "確認密碼",
      fullName: "全名",
      createAccount: "建立帳戶",
      alreadyHaveAccount: "已經有帳戶？",
      dontHaveAccount: "沒有帳戶？",
      loginHere: "在此登入",
      registerHere: "在此註冊",
      welcomeBack: "歡迎回來",
      enterCredentials: "輸入您的登入資料以進入帳戶",
      signingIn: "登入中...",
      signIn: "登入",
      createAccountNow: "立即建立",
      secureLogin: "由 Firebase 認證提供安全登入",
      signInToContinue: "登入以繼續",
      emailPlaceholder: "your.email@example.com",
      passwordPlaceholder: "••••••••",
      fullNamePlaceholder: "陳大文",
      noAccountFound: "此電郵未有對應帳戶。",
      incorrectPassword: "密碼錯誤。",
      invalidEmail: "電郵地址無效。",
      failedLogin: "登入失敗。請檢查登入資料。",
      joinCommunity: "加入我們的化學學習社群",
      creatingAccount: "建立帳戶中...",
      passwordsNoMatch: "密碼不相符",
      passwordMinLength: "密碼至少需要 6 個字符",
      enterFullName: "請輸入您的全名",
      emailAlreadyInUse: "此電郵已被使用。",
      weakPassword: "密碼太弱。請至少使用 6 個字符。",
      failedCreateAccount: "建立帳戶失敗。請重試。",
      minimumCharacters: "最少 6 個字符",
      secureRegistration: "由 Firebase 提供安全註冊",
      switchToChinese: "切換至繁體中文",
      switchToEnglish: "切換至英文",
      languageNameChinese: "繁體中文",
      languageNameEnglish: "英文",
    },

    profile: {
      profileSettings: "個人資料設定",
      yourStatistics: "您的統計",
      displayName: "顯示名稱",
      email: "電郵地址",
      schoolLevel: "年級（中四／中五／中六）",
      studyLevel: "目前學習程度",
      memberSince: "加入日期",
      saveChanges: "儲存變更",
      topicExceptions: "主題例外",
      unlockTopic: "解鎖主題",
      lockTopic: "鎖定主題",
      manageAccount: "管理您的帳戶與學習偏好",
      totalAttempts: "總測驗次數",
      overallAccuracy: "整體準確率",
      questionsSolved: "已完成題目",
      accountInformation: "帳戶資料",
      profileUpdated: "個人資料已成功更新！",
      failedUpdate: "更新個人資料失敗。請重試。",
      enterYourName: "輸入您的名稱",
      emailCannotChange: "電郵地址無法更改",
      selectCurrentForm: "選擇您目前年級（中四／中五／中六）",
      topicsLearnedUpTo: "已學習至",
      selectHighestTopic: "選擇您已學到的最高主題編號。例如：選擇「08」代表您已學習 01–08。",
      topicExceptionsLabel: "主題例外",
      clickToExclude: "點擊主題以從練習中排除",
      yourAvailableTopicsCount: "您可用的主題",
      theseTopicsWillAppear: "這些主題會出現在練習模式中",
      saving: "儲存中...",
      profilePicture: "個人頭像",
      preview: "預覽",
      onlyOwnedItems: "只能使用您擁有（或免費）的物品。",
      icon: "圖示",
      background: "背景",
    },

    notebook: {
      title: "錯題簿",
      commandCenter: "自訂錯題重温",
      mistakeDeck: "錯題卡組",
      learningInsights: "學習洞察",
      learningAnalytics: "學習分析",
      archive: "封存",
      masteryArchive: "精通封存",
      questionsHidden: "此頁不顯示題目內容，請開始測驗查看。",

      filterInfoTitle: "關於主題/副題篩選",
      filterInfoBody: "主題/副題篩選會搜尋你所有的錯題記錄，不只限於畫面上顯示的首 40 題。你可以按 \"Load more\" 來顯示更多結果。",
      close: "關閉",

      activeFilters: "已套用篩選",
      clearAll: "清除全部",

      review: "複習錯題",
      practiceMistakes: "只練錯題",
      practiceMistakesCount: "練習 {count} 題錯題",
      practiceSelected: "練習已選 {count} 題",
      cleared: "所有錯題已清除！",
      addedToNotebook: "已加入錯題簿",
      removedFromNotebook: "已從錯題簿移除",
      reviewMaster: "重溫並精通您答錯的題目",

      questionDetail: "題目詳情",
      question: "題目",
      options: "選項",
      viewFullQuestion: "查看完整題目",
      viewFull: "查看完整",
      attempts: "嘗試次數",
      masteryLevelLabel: "掌握程度",
      lastAttemptedLabel: "最後嘗試",

      totalMistakes: "錯題總數",
      topicsToFocus: "需加強主題",
      repeatedMistakes: "重複錯題",

      customReview: "自訂重溫",
      customReviewSubtitle: "設定你的練習時段",
      sessionPreview: "練習預覽",
      willPractice: "本次練習",
      masteryBreakdown: "分佈",
      custom: "自訂",
      timerSettings: "計時",

      configurePractice: "設定練習",
      numberOfQuestions: "題數",
      questionsLabel: "1. 題目數量",
      questionsAvailable: "可用",
      questionsAvailableFull: "在目前篩選條件下可用的題目",
      timeRange: "時間範圍",
      timeRangeLabel: "2. 時間範圍（何時出現錯題）",
      allTime: "全部",
      lastMonth: "最近一個月",
      lastWeek: "最近一週",
      default: "預設",

      topics: "主題",
      topicsLabel: "3. 主題（留空代表全部）",
      subtopics: "子主題",
      subtopicsFilteredNote: "（會隨已選主題篩選）",
      masteryLevel: "掌握程度",
      srsPresence: "SRS",
      srsPresenceAll: "全部",
      srsPresenceInSrs: "在 SRS 內",
      srsPresenceNotInSrs: "不在 SRS",
      clearTopicFilter: "✕ 清除主題篩選",
      clearSubtopicFilter: "清除子主題篩選",
      clearMasteryFilter: "清除掌握程度篩選",
      filteredFrom: "篩選自",
      clearSelection: "清除選擇",

      masteryNotInSrs: "不在 SRS",
      masteryNew: "新",
      masteryDeveloping: "發展中",
      masteryProgressing: "進步中",
      masteryNear: "接近精通",
      masteryMastered: "已精通",
      mastered: "已精通",
      statusUnprocessed: "未處理",
      statusInProgress: "進行中",
      statusNearMastery: "接近精通",

      allMistakes: "所有錯題",
      noMistakesYet: "暫無錯題！",
      keepPracticing: "繼續練習，答錯的題目會在此出現。",
      startPracticing: "開始練習",
      noQuestionsFound: "沒有題目符合篩選條件",
      tryAdjustFilters: "嘗試調整篩選設定",
      noArchivedYet: "尚未有封存題目",
      archiveInstructions: "封存分為兩種：精通（SRS）及逾期（自動整理）",
      archiveSubtabMastery: "精通",
      archiveSubtabOverdue: "逾期",
      archiveSubtabCount: "顯示 {count} 題",

      archiveMasteryHowTitle: "精通封存（SRS）",
      archiveMasteryHowBody: "當題目在 SRS 中累積 5 次答對（成功複習）後，會進入「精通封存」。複習間隔：第 1 次答對 → 1 天、第 2 次答對 → 6 天，其後間隔會按「目前間隔 × 容易度」逐步拉長。若答錯，進度會重置（成功次數回到 0），並回到 1 天後再複習。",
      archiveOverdueHowTitle: "逾期封存（自動整理）",
      archiveOverdueHowBody: "當題目到期（next review date）後仍未複習，並且逾期超過 14 天，系統會自動封存以減少提醒噪音。你可隨時在此還原。",

      noMasteryArchives: "暫未有精通封存",
      noMasteryArchivesHint: "持續按 SRS 複習，累積 5 次答對後就會畢業封存。",
      noOverdueArchives: "暫未有逾期封存",
      noOverdueArchivesHint: "當到期後逾期 14+ 天仍未複習，便會出現在此。",
      allCaughtUp: "已全部完成！",

      lastAttempt: "上次嘗試",
      missed: "錯 {count} 次",
      yourAnswer: "您的答案",
      correctAnswer: "正確答案",
      correct: "正確",
      explanation: "解釋",
      priority: "優先度",

      howItWorks: "運作方式",
      wrongAnswersAutoSaved: "答錯的題目會自動保存到此",
      useFilters: "使用篩選器專注於特定主題或近期錯題",
      practiceUntilMaster: "練到您真正掌握！",
      clearAfterThreeCorrect: "✨ 連續答對 3 次後，題目會自動清除！",

      loadingMistakes: "載入錯題中...",
      sessionLimited: "練習最多限制為 {max} 題。",

      topicBreakdown: "主題分析",
      hoverForDetails: "將滑鼠移到統計上查看詳情",
      weakTopics: "薄弱主題",
      focusTheseTopics: "專注於這些主題",
      repeatsByTopic: "按主題統計的重複錯題",
      needMorePractice: "需要更多練習",
      improved: "已改善 {count}",

      retentionDashboard: "記憶保留儀表板",
      addedThisWeek: "新增（7 天）",
      masteredThisWeek: "精通（7 天）",
      decayRate: "遺忘率",
      decayImproving: "改善中",
      decayStable: "穩定",
      decayGrowing: "上升",
      weakestSubtopics: "最薄弱子主題",
      urgentReviews: "最緊急重溫（按優先分數）",

      priorityScore: "間隔重複優先分數",

      errorTypeLabel: "錯誤類型：",
      tagErrorType: "標記錯誤類型",
      errorCategory: "錯誤分類",
      clearTag: "清除標記",
      errorTypeMisread: "看錯題目",
      errorTypeConceptual: "概念不足",
      errorTypeCalculation: "計算錯誤",
      errorTypeCareless: "粗心大意",
      errorTypeVocab: "詞彙不足",
      errorTypeDiagram: "看錯圖表",
      errorMisread: "看錯題目",
      errorConceptual: "概念不足",
      errorCalculation: "計算錯誤",
      errorCareless: "粗心大意",
      errorVocabulary: "詞彙不足",
      errorDiagram: "看錯圖表",
      tagError: "標記錯誤",

      spacedRepetitionNote: "卡片按間隔重複優先度排序——越緊急越前。",
      metacognitiveNote: "為每題錯題標記錯誤分類，以追蹤您的常見模式。",

      mistakeClearingActivity: "SRS 錯題清除活動",
      errorDensityByTopic: "按主題的錯誤密度",
      improvementTrend: "SRS 改善趨勢（14 天）",
      srsTrendTitle: "SRS 改善趨勢（14 天）",
      srsTrendSubtitle: "說明此圖表的意義，以及如何解讀。",
      srsTrendPurposeTitle: "用途",
      srsTrendPurposeBody: "此圖表協助你快速了解：你是否仍常在第一次複習時答錯、是否正在累積練習量，或是否正在把題目推向精通。",
      srsTrendMechanicsTitle: "運作方式",
      srsTrendMechanicsBody: "系統會將你每天的複習按學習階段分組。數字會每天上升或下降，因為這裡顯示的是「當日活動量」，而不是累積總數。",
      srsTrendBucketsTitle: "各階段的意義",
      srsTrendNewDesc: "你在第一次 SRS 複習該題時答錯。",
      srsTrendDevelopingDesc: "你正在練習該題。包含第一次複習答對的題目，以及之後因答錯而退回來的題目。",
      srsTrendNearDesc: "你已多次答對該題，因此複習間隔會逐漸拉長。",
      srsTrendMasteredDesc: "你已達到畢業條件（例如成功複習 5 次）。",
      srsTrendHowToReadTitle: "如何解讀圖表",
      srsTrendHowToReadBody: "柱狀越高代表當天在該階段的複習量越多。若某階段今日降為 0，通常只是表示今天較少（或沒有）該階段的複習，並不代表你失去進度。",
      srsTrendInfoAria: "開啟 SRS 改善趨勢說明",
      srsClearingInfoAria: "開啟 SRS 清除活動說明",
      srsClearingTitle: "SRS 錯題清除活動",
      srsClearingSubtitle: "說明此熱度圖的指標，以及為何某些日期可能為 0。",
      srsClearingPurposeTitle: "用途",
      srsClearingPurposeBody: "此熱度圖用於追蹤你的學習規律。它會顯示你每天成功清除（答對）的 SRS 複習數量。",
      srsClearingMechanicsTitle: "運作方式",
      srsClearingMechanicsBody: "當天成功清除的複習越多，色塊就會越深。若顯示為 0，通常代表當天沒有成功清除任何 SRS 複習。",
      selectedCount: "已選 {count}",
      weekdaySunShort: "日",
      weekdayMonShort: "一",
      weekdayTueShort: "二",
      weekdayWedShort: "三",
      weekdayThuShort: "四",
      weekdayFriShort: "五",
      weekdaySatShort: "六",
      activityTooltipCleared: "{date}：清除 {count} 題",
      questionDiagramAlt: "題目圖表",
      clickTopicToFilter: "點擊主題以篩選 →",
      clickTopicsToFilter: "點擊主題以篩選（可多選）",
      less: "較少",
      more: "較多",

      aiDailyMission: "AI 每日任務",
      aiDailyMissionNote: "AI 會智能挑選 10 題並穿插練習，以最大化記憶保留。",
      needMoreQuestions: "需要 10+ 道錯題（目前 {count}）",
      interleavedPractice: "10 題 • 穿插練習",

      timerEnabled: "顯示計時",
      timedMode: "限時模式",

      listView: "清單檢視",
      kanbanView: "看板檢視",
      selectAll: "全選",

      mastered: "已精通",
      masteredOn: "於 {date} 精通",
      archivedAt: "封存於",

      topicFilter: "主題：{topic}",
    },

    leaderboard: {
      title: "排行榜",
      weeklyTitle: "每周排行榜",
      thisWeek: "本週",
      thisMonth: "本月",
      allTime: "全期",
      yourRank: "您的排名",
      you: "你",
      rankAriaLabel: "排名 {rank}",
      rankTitle: "#{rank}",
      noRankLastWeek: "上週沒有排名",
      noRankLastMonth: "上月沒有排名",
      alreadyClaimed: "已領取",
      tokensAwarded: "+{count} 鑽石！",
      noReward: "沒有獎勵",
      claimFailed: "領取失敗",
      claimReward: "領取獎勵",
      claimed: "已領取",
      claimNow: "立即領取",
      claimedThisPeriod: "本期已領取",
      notEligible: "不符合資格",
      learnMore: "了解更多",
      attempts: "次",
      questions: "題",
      seeHowYouRank: "看看你在其他同學中的排名",
      noDataYet: "暫無數據",
      beFirstComplete: "成為第一個完成測驗的人！",
      howRankingsWork: "排名如何計算：",
      averageScoreLast7: "最近 7 天內所有測驗的平均分",
      averageScoreLast30: "最近 30 天內所有測驗的平均分",
      overallAccuracyAllTime: "所有歷史測驗的整體準確率",
      formLevel: "S4/S5/S6 = 年級",
      flameStreak: "火焰 = 連續學習天數",
    },

    calendar: {
      smartStudyCalendar: "智能學習日曆",
      smartStudyCalendarFeatures: "智能學習日曆功能",
      srsReviewMechanismTitle: "SRS 重溫系統",
      srsReviewMechanismDesc: "SRS（間隔重複系統）在最理想的間隔安排重溫：第 1 次在 1 天後，第 2 次在 6 天後，其後按間隔 × 容易度（預設 2.5）計算。答錯會重置進度。成功重溫 5 次後，題目會畢業並進入精通封存。",
      srsFormulaTitle: "SRS 公式",
      srsFormulaBody: "• 第 1 次答對 → 1 天\n• 第 2 次答對 → 6 天\n• 第 3 次或之後答對 → 間隔 × 容易度（2.5）\n• 答錯 → 重置為 0，1 天",
      srsGraduationTitle: "畢業",
      srsGraduationDesc: "成功重溫 5 次後，題目會進入 {archiveName}，並不再顯示於每日重溫。",
      aiSuggestionsByTopicTitle: "AI 建議（按主題）",
      aiSuggestionsByTopicDesc: "建議會根據你在各主題／子主題的準確率趨勢生成；接受後會把學習時段加入日曆。",
      examQuizRevisionPlanTitle: "考試／小測／溫習計劃",
      examQuizRevisionPlanDesc: "新增考試和小測，跟隨跨日分配的練習與溫習計劃，穩步進步。",
      mechanicsTitle: "操作方式",
      mechanicsDesc: "點按某一天以查看已安排事項與完成紀錄。完成的練習會變綠並保留，方便追蹤。",
      aiStudyRecommendations: "AI 學習建議",
      suggestionsCount: "{count} 個建議",
      suggestedLabel: "建議日期",
      currentLabel: "目前",
      addToCalendar: "加入日曆",
      dismiss: "略過",
      review: "重溫",
      aiLabel: "AI",
      doneCount: "完成 {count}",
      timeMinsSecs: "{m}分 {s}秒",
      timeSecs: "{s}秒",
      thisTopic: "此主題",
      questionsStillLoading: "題目仍在載入中。請稍後再試。",
      noReviewSessionsFoundForDay: "此日沒有重溫時段。",
      questionsNotFound: "找不到題目資料庫中的題目。",
      failedStartReviewTryAgain: "開始重溫失敗。請重試。",
      failedStartStudySessionTryAgain: "開始學習時段失敗。請重試。",
      aiRecommendationAddedSuccess: "✅ 已把 AI 建議加入日曆！",
      failedAddRecommendationWithReason: "加入建議到日曆失敗：\n\n{reason}",
      eventTypeEvent: "活動",
      deleteEventConfirm: "刪除這個{eventType}？這將同時移除所有相關的學習建議與重溫。",
      eventDeletedSuccess: "活動已刪除！",
      failedDeleteEventWithReason: "刪除活動失敗：{reason}",
      mcqCount: "{count} 題 MCQ",
      noQuestionsAvailableForTopicSubtopic: "{topic}{subtopic} 沒有可用題目。",
      noQuestionsAvailableForSuggestion: "{topic}{subtopic} 沒有可用題目。\n\n請確認題庫包含此主題。",

      start: "開始",
      loadFirst40: "先載入 40 題",
      loadMore: "載入更多",
      clickLoadToPreviewQuestions: "按「先載入 40 題」以預覽及開始。",
      srsOverdueDays: "逾期 {count} 天",
      studySessionPreviewTitle: "學習時段預覽",
      phaseLabel: "階段",
      scheduledEvents: "已安排活動",
      legendQuiz: "小測",
      legendStudyPlan: "學習計劃",
      legendAiSuggestion: "AI 建議",
      addEvent: "新增活動",
      addEventSubtitle: "安排考試或小測並獲得智能學習計劃",
      addExamQuiz: "新增考試／小測",
      addAnotherEvent: "新增另一個活動",
      today: "今天",
      studyPlannerTitle: "學習計劃",
      studyPlannerSubtitle: "智能安排・間隔重複",
      eventTypes: "活動類型",
      eventTypeMajorExam: "大型考試",
      eventTypeSmallQuiz: "小測",
      eventTypeStudySuggestion: "溫習建議",
      eventTypeMistakeReview: "SRS 重溫",
      eventTypeCompletedActivity: "已完成",
      eventsCount: "{count} 個活動{plural}",
      scheduledEventsCount: "{count} 個已排程活動{plural}",
      noEventsScheduled: "尚未安排活動",

      weekdaySunShort: "日",
      weekdayMonShort: "一",
      weekdayTueShort: "二",
      weekdayWedShort: "三",
      weekdayThuShort: "四",
      weekdayFriShort: "五",
      weekdaySatShort: "六",

      eventType: "活動類型",
      eventTypeRequired: "活動類型 *",
      majorExam: "大型考試",
      majorExamDesc: "10 天溫習計劃（循序加強）",
      smallQuiz: "小測",
      smallQuizDesc: "3 天重點溫習計劃",

      examQuizDate: "考試／小測日期",
      dateInputPlaceholder: "MM/DD 或 YYYY/MM/DD（例如：12/25 或 2024/12/25）",
      dateQuickLabel: "快速：",
      dateFullLabel: "完整：",
      invalidDateHelp: "請輸入有效日期：\n\n• MM/DD（使用本年度）\n• YYYY/MM/DD（指定年份）\n\n例子：12/25 或 2024/12/25",
      pastDateWarningConfirm: "提示：此日期已過去。\n\n仍要繼續嗎？",

      filterTopicsSubtopics: "篩選主題與子主題",
      topicsCount: "主題（{selected}/{total}）",
      topicsCountFull: "{selected}/{total} 個主題{plural}",
      subtopicsCount: "子主題（{selected}/{total}）",
      subtopicsCountFull: "{selected}/{total} 個子主題{plural}",
      selectAllTopicsUpToTitle: "選取直到並包括「{topic}」的所有主題",
      selectAllSubtopicsUpToTitle: "選取直到並包括「{subtopic}」的所有子主題",
      upToHint: "點擊「到此為止」以選取直到該項目",
      subtopicsAutoFilterHint: "子主題會按已選主題自動篩選",
      selectTopicsToFilterSubtopics: "請先選擇主題以篩選子主題",
      noSubtopicsAvailable: "沒有可用子主題",

      customTitle: "自訂標題",
      autoTitlePlaceholder: "自動：{title}",
      comprehensiveExam: "綜合考試",
      comprehensiveQuiz: "綜合小測",
      topicsExamTitle: "{topics}{ellipsis} 考試",
      topicsQuizTitle: "{topics}{ellipsis} 小測",

      autoGeneratedStudyPlan: "自動生成溫習計劃",
      planMajor10to7Label: "距離 10–7 天：",
      planMajor10to7Desc: "每日 10 題（熱身）",
      planMajor6to4Label: "距離 6–4 天：",
      planMajor6to4Desc: "每日 20 題（鞏固）",
      planMajor3to1Label: "距離 3–1 天：",
      planMajor3to1Desc: "每日 40 題（衝刺）",
      planSmall3Label: "距離 3 天：",
      planSmall3Desc: "5 題（初步重溫）",
      planSmall2Label: "距離 2 天：",
      planSmall2Desc: "10 題（主題集中）",
      planSmall1Label: "距離 1 天：",
      planSmall1Desc: "15 題（最後整理）",
      focusLabel: "重點：",
      allTopics: "所有主題",
      topicCountLabel: "{count} 個主題",
      subtopicCountLabel: "{count} 個子主題",

      creating: "建立中...",
      createEventAndStudyPlan: "建立活動及溫習計劃",
      eventCreatedSuccess: "活動已成功建立！",
      failedCreateEventWithReason: "建立活動失敗：\n\n{reason}",

      pleaseFillRequiredFields: "請填寫所有必填欄位",
      automaticPrepSuggestionsWillBeGenerated: "將會自動生成準備建議",
      titleRequired: "標題 *",
      titlePlaceholder: "例如：化學中期考試",
      dateRequired: "日期 *",
      topicRequired: "主題 *",
      topicPlaceholder: "例如：有機化學",
      subtopicOptional: "子主題（可選）",
      subtopicPlaceholder: "例如：反應機理",
      automaticSuggestions: "自動建議：",
      automaticSuggestionsMajor: "10/20/40 題溫習計劃（距離 10–7、6–4、3–1 天）",
      automaticSuggestionsSmall: "快速重溫 5–15 題（距離 3–1 天）",
      createEvent: "建立活動",
      clickToStartPractice: "點擊開始練習 →",
    },

    forum: {
      title: "MCQ 討論區",
      discuss: "討論",
      discussion: "討論",
      categoryGeneral: "一般",
      categoryQuestion: "問題",
      categoryAnnouncement: "公告",
      addComment: "新增留言",
      editComment: "編輯留言",
      deleteComment: "刪除留言",
      noComments: "暫時沒有留言。來做第一個討論吧！",
      noCommentsYet: "暫時沒有留言",
      beFirstToShareThoughts: "成為第一個分享想法的人！",
      loading: "載入討論中...",
      popular: "熱門",
      questionsWithDiscussions: "題有討論",
      noResultsFound: "找不到結果",
      noMcqDiscussions: "尚未有 MCQ 討論。可從任何測驗開始討論！",
      connectDiscuss: "與其他同學交流討論",
      comments: "留言",
      delete: "刪除",
      viewMore: "查看更多",
      searchPosts: "搜尋帖子...",
      all: "全部",
      newPost: "新帖子",
      noPosts: "尚未有帖子。做第一個吧！",
      createPost: "建立帖子",
      backToForum: "返回討論區",
      edited: "已編輯",
      save: "儲存",
      cancel: "取消",
      replies: "回覆",
      writeReply: "撰寫回覆...",
      reply: "回覆",
      pleaseLoginReply: "請登入以回覆。",
      createNewPost: "建立新帖子",
      category: "分類",
      title2: "標題",
      enterClearTitle: "輸入清晰、具描述性的標題",
      content: "內容",
      shareThoughts: "分享你的想法、問題或公告...",
      post: "發佈",
      deletePost: "刪除這個帖子？",
      deleteReply: "刪除這個回覆？",
      notifications: "通知",
      markAllRead: "全部設為已讀",
      deleteAll: "全部刪除",
      deleteAllNotificationsTitle: "要刪除所有通知嗎？",
      deleteAllNotificationsBody: "此操作會永久刪除所有通知，且無法復原。",
      deleteAllNotificationsConfirm: "要刪除所有通知嗎？",
      noNotificationsYet: "暫時沒有通知",
      postNotFound: "找不到此帖子。",
      likedYourComment: "讚好了你的留言",
      repliedToPost: "回覆了你的帖子",
      likedYourPost: "讚好了你的帖子",
      likedYourReply: "讚好了你的回覆",
      repliedToComment: "回覆了你的留言",
      interactedWithContent: "與你的內容互動",
      justNow: "剛剛",
      mcqDiscussion: "MCQ 討論",
      generalForum: "一般討論區",
      searchQuestions: "搜尋題目、主題、DSE code...",
      recent: "最新",
      editExpired: "可編輯時間已過（15 分鐘）。",
      editWindowExpired: "編輯期限已過",
      editExpiredLong: "可編輯時間已過（15 分鐘），你不能再編輯此留言。",
      editWindowLabel: "可編輯時間：",
      editLocked: "已鎖定編輯",
      editIn: "{remaining} 後可編輯",
      confirmDeleteComment: "確定要刪除這則留言嗎？",
      failedDeleteComment: "刪除留言失敗",
      failedUpdateComment: "更新留言失敗",
      failedAddCommentWithReason: "新增留言失敗：{reason}",
      failedReplyWithReason: "回覆失敗：{reason}",
      pleaseLoginToLikeComments: "請登入以讚好留言",
      pleaseLoginJoinDiscussion: "請登入以加入討論",
      shareYourThoughts: "分享你的想法...",
      hideReplies: "隱藏回覆",
      commentsCount: "{count} 則留言",
      timeAgoMinutes: "{count} 分鐘前",
      timeAgoHours: "{count} 小時前",
      timeAgoDays: "{count} 天前",
      timeAgoMinutesShort: "{count}分",
      timeAgoHoursShort: "{count}小時",
      timeAgoDaysShort: "{count}天",
    },

    history: {
      title: "練習歷史",
      clickToSeeAnalysis: "點擊任何記錄以查看完整分析",
      viewingAttemptFromCalendar: "正在查看從日曆開啟的記錄",
      totalAttempts: "總測驗次數",
      averageScore: "平均分",
      bestScore: "最高分",
      totalTime: "總用時",
      filtersAndSorting: "篩選與排序",
      timePeriod: "時間範圍",
      allTime: "全部",
      lastMonth: "最近一個月",
      lastWeek: "最近一週",
      sortBy: "排序方式",
      recent: "最新",
      score: "分數",
      time: "時間",
      yourAttempts: "您的記錄",
      clickViewAnalysis: "點擊查看完整分析",
      refresh: "刷新",
      noAttemptsFound: "找不到記錄",
      tryChangingFilter: "嘗試更改時間範圍",
      startPracticingHistory: "開始練習以在此查看歷史記錄！",
      takeFirstQuiz: "開始第一個測驗",
      correct: "正確",
      loadingHistory: "載入歷史記錄中...",
      timeHrsMins: "{h}小時 {m}分鐘",
      timeMinsSecs: "{m}分鐘 {s}秒",
      timeSecs: "{s}秒",
    },

    store: {
      title: "ChemStore",
      subtitle: "使用鑽石解鎖專屬物品",
      yourBalance: "您的餘額",
      profilePics: "頭像",
      badges: "徽章",
      themes: "主題",
      equipped: "已裝備",
      equip: "裝備",
      buy: "購買",
      claim: "領取",
      locked: "未解鎖",
      buying: "購買中...",
      comingSoon: "即將推出！",
      howToEarnTokens: "如何獲得鑽石",
      correctAnswers: "答對題目：",
      correctAnswersTokens: "每答對 2 題獲得 1 鑽石。",
      quizBonus: "測驗獎勵（10 題或以上）：",
      quizBonusTokens: "100% = 20 鑽石，80%+ = 15 鑽石，50%+ = 10 鑽石",
      dailyReward: "每日獎勵：",
      dailyRewardTokens: "每天 5 鑽石",
      weeklyLeaderboard: "每週排行榜：",
      weeklyLeaderboardTokens: "第 1 名 = 30 鑽石，第 2 名 = 27，第 3 名 = 24，...",
      millionaireGame: "百萬富翁遊戲：",
      millionaireGameTokens: "到達更高題目可獲得更多鑽石（根據關卡 1-100 鑽石）",
      notEnoughTokens: "鑽石不足！",
      purchased: "已購買 {name}！",
      purchaseFailed: "購買失敗",
      failedToEquip: "裝備失敗",
      pleaseTryAgain: "請再試一次。",
      failedToEquipItem: "裝備物品失敗",
    },

    tokenLog: {
      title: "鑽石歷史",
      subtitle: "查看你的獲得與消費記錄",
      totalEarned: "總獲得",
      totalSpent: "總消費",
      allTransactions: "全部交易",
      gains: "收入",
      spends: "支出",
      recentTransactionsCount: "最近交易（{count}）",
      noTransactionsYet: "暫無交易",
      noEarningsYet: "暫無收入",
      noPurchasesYet: "暫無消費",
      completeQuizzesToEarn: "完成測驗即可開始賺取鑽石！",
      balanceAfterTokens: "交易後餘額：{balance} 鑽石",
      unknown: "未知",
    },

    // Practice Mode Selection
    practiceMode: {
      updateYourTopics: "更新您的主題",
      learnedUpTo: "已學習至：",
      exceptions: "例外（未學習）：",
      saveChanges: "儲存變更",
      updating: "更新中...",
      topicsUpdated: "主題已成功更新！",
      failedUpdate: "更新主題失敗",
      configureCustomSession: "自訂練習設定",
      back: "返回",
      selectTopics: "1. 選擇主題（可多選）",
      lockedTopicsNotLearned: "鎖定的主題尚未學習。請在個人資料中更新或點擊上方按鈕。",
      focusSubtopics: "2. 選擇子主題（可選）",
      sessionLength: "3. 練習題數",
      generateExam: "開始練習",
      startPractice: "開始練習",
    },
  },
};

// ...

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    return normalizeLanguageCode(localStorage.getItem('chemleung_language') || 'en');
  });

  useEffect(() => {
    localStorage.setItem('chemleung_language', language);
  }, [language]);

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'en' ? 'zh' : 'en');
  };

  const setLanguageNormalized = (next) => {
    setLanguage(normalizeLanguageCode(next));
  };

  const t = (key) => {
    const keys = key.split('.');
    const tryResolve = (langRoot) => {
      let value = langRoot;
      for (const k of keys) {
        if (value && typeof value === 'object') {
          value = value[k];
        } else {
          return undefined;
        }
      }
      return value;
    };

    const primary = tryResolve(translations[language]);
    if (primary !== undefined && primary !== null) return primary;

    const fallback = tryResolve(translations.en);
    if (fallback !== undefined && fallback !== null) return fallback;

    return key;
  };

  const tf = (key, params = {}) => {
    let text = t(key);
    Object.keys(params).forEach(param => {
      text = text.replace(`{${param}}`, params[param]);
    });
    return text;
  };

  const value = {
    language,
    setLanguage: setLanguageNormalized,
    toggleLanguage,
    t,
    tf,
    isEnglish: language === 'en',
    isChinese: language === 'zh',
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}