import React, { createContext, useState, useContext, useEffect } from 'react';

const LanguageContext = createContext();

export function useLanguage() {
  return useContext(LanguageContext);
}

// Translation dictionary
const translations = {
  en: {
    // Branding
    appName: "ChemLeung HKDSE MCQ Practice Platform",
    tagline: "HKDSE Chemistry Practice",
    
    // Navigation
    nav: {
      dashboard: "Dashboard",
      practice: "Practice",
      leaderboard: "Leaderboard",
      history: "History",
      profile: "Profile",
      logout: "Logout",
    },

    header: {
      tokens: "tokens",
      myHistory: "My History",
      tokenHistory: "Token History",
      logoutWarning: "You will be logged out of your account. Any unsaved progress will be lost.",
      confirmLogoutInQuiz: "Are you sure you want to logout?\n\n⚠️ You are in the middle of a quiz. Your progress will be lost!",
      confirmLeaveQuiz: "Are you sure you want to leave the quiz?\n\n⚠️ Your current progress will be lost!",
    },
    
    // Dashboard
    dashboard: {
      welcomeBack: "Welcome back",
      totalAttempts: "Total Attempts",
      overallAccuracy: "Overall Accuracy",
      questionsSolved: "Questions Solved",
      correctAnswers: "Correct Answers",
      studyStreak: "Study Streak",
      days: "days",
      startNewQuiz: "Start New Quiz",
      viewLeaderboard: "View Leaderboard",
      recentAttempts: "Recent Attempts",
      noAttempts: "No attempts yet!",
      takeFirstQuiz: "Take Your First Quiz",
      browseForm: "Browse Forum",
      mistakeNotebook: "Mistake Notebook",
      logout: "Logout",
      confirmLogout: "Confirm Logout",
      areYouSureLogout: "Are you sure you want to logout?",
      needSignInAgain: "You will need to sign in again to access your account and continue practicing.",
      cancel: "Cancel",
      errorLoadingAttempts: "Error Loading Attempts",
      retry: "Retry",
      clickRowFullAnalysis: "Click any row to see full analysis",
      refresh: "Refresh",
      noDataYet: "No data yet",
      completeQuizSeeResults: "Complete a quiz to see your results here",
      correct: "correct",
      timeSpent: "Time spent",
      loadingDashboard: "Loading dashboard...",

      howThisWorks: "How this works",
      priorityReviewTitle: "Priority Review",
      top3UrgentMistakes: "Top 3 Urgent Mistakes (ISRS Algorithm)",
      priorityReviewEmpty: "No mistakes tracked yet. Complete quizzes and log your mistakes to get personalized review recommendations!",
      priorityReviewMechanismTitle: "Priority Review mechanism",
      priorityReviewMechanismDesc: "This panel surfaces the top 3 most urgent mistakes using the ISRS priority score.",
      whatIncreasesPriorityTitle: "What increases priority",
      whatIncreasesPriorityDesc: "More recent wrong attempts, repeated mistakes, and topics you've studied recently.",
      whatQuickFixDoesTitle: "What \"Quick Fix\" does",
      whatQuickFixDoesDesc: "Starts a focused practice session for that specific question so you can fix it immediately.",
      priorityCritical: "Critical",
      priorityHigh: "High",
      priorityMedium: "Medium",
      priorityLabel: "{level} Priority",
      questionTextNotAvailable: "Question text not available",
      attempts: "Attempts",
      correct: "Correct",
      quickFix: "Quick Fix",
      viewFullMistakeNotebook: "View Full Mistake Notebook",

      masteryHealthBarTitle: "Mastery Health Bar",
      ruleOf3Subtitle: "Based on the Rule of 3 system",
      masteryHealthBarMechanismTitle: "Mastery Health Bar mechanism",
      masteryMechanismDesc: "Topics move through 3 states based on correct attempts (the Rule of 3).",
      masteryNewTitle: "New",
      masteryNewDesc: "Not attempted yet.",
      masteryImprovingTitle: "Improving",
      masteryImprovingDesc: "1–2 correct answers.",
      masteryMasteredTitle: "Mastered",
      masteryMasteredDesc: "3+ correct answers.",
      masteryBarExplainer: "The bar shows your syllabus coverage split into these 3 categories.",
      syllabusCoverage: "Syllabus Coverage",
      topicsTrackedCount: "{count} Topics Tracked",
      unseenTooltip: "{pct}% Unseen ({count} topics)",
      improvingTooltip: "{pct}% Improving ({count} topics)",
      masteredTooltip: "{pct}% Mastered ({count} topics)",

      quickStatsTitle: "Quick Stats",
      quickStatsMechanismTitle: "Quick Stats mechanism",
      quickStatsMechanismDesc: "This section summarizes your learning momentum and progress at a glance.",
      quickStatsStudyStreakTitle: "Study Streak",
      quickStatsStudyStreakDesc: "Counts consecutive days you studied (based on recent activity).",
      quickStatsTopicsMasteredTitle: "Topics Mastered",
      quickStatsTopicsMasteredDesc: "How many topics have reached the mastered threshold in the mastery system.",
      quickStatsInProgressTitle: "In Progress",
      quickStatsInProgressDesc: "Topics you’ve started but haven’t mastered yet (keep practicing to push them over the line).",

      quizSessionsCount: "{count} Quiz Session(s)",
      correctOutOfTotal: "{correct}/{total} Correct",
      clickAnyAttempt: "Click any attempt",
      toSeeDetailedAnalysis: "to see detailed analysis and insights",

      priorityReviewAiStudySuggestionTitle: "Priority Review: AI Study Suggestion",
      aiStudySuggestionsEmpty: "No AI suggestions yet. Keep practicing to unlock personalized recommendations.",
      aiStudySuggestionsMechanismTitle: "AI Study Suggestions",
      aiStudySuggestionsMechanismDesc: "These suggestions are generated from your recent performance by topic/subtopic. Accepting one adds a recommended study session into your calendar.",
    },

    srs: {
      title: "Spaced Repetition Review",
      failedLoadDueCardsTryAgain: "Failed to load due cards. Please try again.",
      loadingDueCards: "Loading due cards...",
      pleaseSelectAtLeastOne: "Please select at least one question to review.",
      questionsStillLoading: "Questions are still loading. Please wait a moment and try again.",

      questionsNeedReviewCount: "{count} question{plural} need review",
      reviewMode: "Review Mode",
      quickReview: "Quick Review",
      aiSelectsRandomQuestions: "AI selects random questions",
      defaultBadge: "✓ DEFAULT",
      singleQuestion: "Single Question",
      reviewOneMistake: "Review one mistake",
      customBatch: "Custom Batch",
      selectSpecificCards: "Select specific cards",
      numberOfQuestions: "Number of Questions",
      nQuestions: "{count} Questions",
      allCount: "All ({count})",

      timerSettings: "Timer Settings",
      enableTimer: "Enable Timer",
      timedMode75sPerQuestion: "Timed Mode (75s per question)",
      mustAnswerWithin75SecondsPerQuestion: "You must answer within 75 seconds per question",
      timerTracksSpeedNoLimit: "Timer tracks your speed but no time limit",
      noTimerTracking: "No timer tracking",
      timedModeSummary75: "Timed Mode: 75s/question",
      timerTrackingEnabled: "Timer tracking enabled",
      noTimer: "No timer",

      selectCardsToReview: "Select Cards to Review",
      selectedCountOutOfTotal: "{selected} / {total} selected",
      deselectAll: "Deselect All",
      selectAll: "Select All",
      dueLabel: "Due",
      noTopic: "No Topic",
      noDueCardsMatchFilters: "No due cards match your filters",
      questionIdLabel: "Question ID",
      intervalLabel: "Interval",
      attemptLabel: "Attempt",
      easeLabel: "Ease",

      startQuickReviewCount: "Start Quick Review ({count} Question{plural})",
      startSingleReview: "Start Single Review",
      startBatchReviewCount: "Start Batch Review ({count} Question{plural})",
    },

    practiceModeCarousel: {
      headerTitle: "Choose Your Practice Mode",
      headerSubtitle: "Select a mode to begin your learning journey",
      previousMode: "Previous mode",
      nextMode: "Next mode",
      startSession: "Start Session",
      clickToSelect: "Click to select",
      selectedLabel: "{mode} Selected",
      selectModeAria: "Select {mode}",

      timedTitle: "Timed Mode",
      timedSubtitle: "1.25 min per question",
      timedDesc: "Perfect for exam simulation",
      marathonTitle: "Marathon Mode",
      marathonSubtitle: "No time pressure",
      marathonDesc: "Take your time and focus",
      aiDailyTitle: "AI Daily Mission",
      aiDailySubtitle: "Smart spaced repetition",
      aiDailyDesc: "AI-optimized learning path",
      mistakeReviewTitle: "Mistake Review",
      mistakeReviewSubtitle: "Master your weaknesses",
      mistakeReviewDesc: "Practice until perfect",
      customTitle: "Custom Session",
      customSubtitle: "Your rules",
      customDesc: "Choose topics & settings",
    },
    
    // Practice Modes
    practice: {
      selectMode: "Select Practice Mode",
      timed: "Timed Practice",
      timedDesc: "Race against the clock - {minutes} minutes",
      marathon: "Marathon Mode",
      marathonDesc: "Unlimited time - track your progress",
      custom: "Custom Session",
      customDesc: "Choose topics and question count",
      startPractice: "Start Practice",
      selectPracticeMode: "Select Practice Mode",
      chooseHowPractice: "Choose how you want to practice today",
      perQuestion: "min per question",
      perfectForExam: "Perfect for exam simulation with a countdown timer.",
      takeYourTime: "Take your time. We'll track duration but no pressure!",
      chooseSpecificTopics: "Choose specific topics, subtopics, and question count.",
      questions: "Questions:",
      configure: "Configure",
      yourAvailableTopics: "Your Available Topics",
      more: "more",
      noTopicsConfigured: "No topics configured!",
      pleaseSetTopics: "Please set which topics you've learned in your Profile settings.",
      goToProfile: "Go to Profile",
      updateTopics: "Update Topics",
    },
    
    // Quiz Interface
    quiz: {
      question: "Question",
      questionPrefix: "Q",
      of: "of",
      flagQuestion: "Flag Question",
      unflagQuestion: "Unflag Question",
      periodicTable: "Periodic Table",
      periodicTableAlt: "Periodic Table",
      overview: "Overview",
      previous: "Previous",
      next: "Next",
      submit: "Submit",
      answered: "Answered",
      flagged: "Flagged",
      skipped: "Skipped",
      timeRemaining: "Time Remaining",
      sessionTime: "Session Time",
      totalTime: "Total Time",
      initializingQuiz: "Initializing quiz...",
      type: "Type",
      toSelect: "to select",
      flag: "flag",
      tools: "Tools",
      backToTopics: "Back to Topics",
      periodicTableOfElements: "Periodic Table of Elements",
      time: "Time",
      thisQuestion: "This Question:",
      questionOverview: "Question Overview",
      tip: "Tip:",
      press: "Press",
      pleaseAnswerAll: "Please answer all questions before submitting.",
      finishSubmit: "Finish & Submit",
      confirmBackToTopics: "Are you sure you want to go back to topic selection?\n\n⚠️ ALL YOUR PROGRESS WILL BE LOST!",
      enableTimer: "Enable Timer",
      trackTimeSpent: "Track time spent on questions",
      showTimer: "Show Timer",
      countdown: "Countdown",
      timedMode: "Timed Mode",
      countdownTimer: "Countdown with time limit",
      timeUp: "Time's up! Your quiz will be submitted now.",
    },
    
    // Results
    results: {
      yourPerformance: "Your Performance",
      totalTime: "Total Time",
      averagePerQuestion: "Average per MCQ",
      strengths: "Strengths",
      needsFocus: "Needs Focus",
      detailedReview: "Detailed Review",
      yourAnswer: "Your Answer",
      correctAnswer: "Correct Answer",
      explanation: "Explanation",
      shareReport: "Share Report Card",
      addToNotebook: "Add to Mistake Notebook",
      startNewSession: "Start New Session",
      savingToProfile: "Saving to your profile...",
      savedToProfile: "Saved to your profile!",
      reviewsSaved: "Reviews saved!",
      saveFailed: "Save Failed",
      continueAnyway: "Continue Anyway",
      resultsSavingLeaveConfirm: "Your quiz results are still being saved. Are you sure you want to leave?",
      resultsMayNotBeSavedLeaveConfirm: "Your results may not be fully saved. Are you sure you want to leave?",
      resultsNotSavedContinueAnywayConfirm: "Your results were not saved. Continue anyway?",
    },

    report: {
      shareReportCard: "Share Report Card",
      downloadPngTitle: "Download as PNG image",
      downloadPdfTitle: "Download as PDF",
      image: "Image",
      pdf: "PDF",
      fileNamePrefix: "ChemLeung-Report",
      website: "www.chemleung.com",
      dismiss: "Dismiss",
      hkDsePracticeReport: "HKDSE Chemistry Practice Report",
      studentName: "Student Name",
      student: "Student",
      topicsCovered: "Topics Covered",
      topicsUnit: "Topics",
      outOf: "out of",
      correctLabel: "Correct",
      correct: "Correct",
      incorrect: "Incorrect",
      timeUsed: "Time Used",
      timeHrsMins: "{h}h {m}m",
      timeMinsSecs: "{m}m {s}s",
      topicBreakdown: "Topic Breakdown",
      generatedBy: "Generated by ChemLeung HKDSE MCQ Practice Platform",
      generating: "Generating report...",
      mayTakeSeconds: "This may take a few seconds",
      reportNotReady: "Report not ready. Please try again.",
      failedCreateImage: "Failed to create image",
      failedExportImageTryPdf: "Failed to export image. Try PDF export instead.",
      failedExportPdfTryImage: "Failed to export PDF. Try image export instead.",
      na: "N/A",
    },
    
    // Profile
    profile: {
      profileSettings: "Profile Settings",
      yourStatistics: "Your Statistics",
      displayName: "Display Name",
      email: "Email Address",
      schoolLevel: "School Level (Form)",
      studyLevel: "Current Study Level",
      memberSince: "Member Since",
      saveChanges: "Save Changes",
      topicExceptions: "Topic Exceptions",
      unlockTopic: "Unlock Topic",
      lockTopic: "Lock Topic",
      manageAccount: "Manage your account and learning preferences",
      totalAttempts: "Total Attempts",
      overallAccuracy: "Overall Accuracy",
      questionsSolved: "Questions Solved",
      accountInformation: "Account Information",
      profileUpdated: "Profile updated successfully!",
      failedUpdate: "Failed to update profile. Please try again.",
      enterYourName: "Enter your name",
      emailCannotChange: "Email address cannot be changed",
      selectCurrentForm: "Select your current form (S4, S5, or S6)",
      topicsLearnedUpTo: "Topics Learned Up To",
      selectHighestTopic: "Select the highest topic number you've learned. For example, '08' means you have learned topics 01-08.",
      topicExceptionsLabel: "Topic Exceptions",
      clickToExclude: "Click topics to exclude them from practice",
      yourAvailableTopicsCount: "Your Available Topics",
      theseTopicsWillAppear: "These topics will appear in practice mode",
      saving: "Saving...",
      profilePicture: "Profile Picture",
      preview: "Preview",
      onlyOwnedItems: "Only items you own (or free items) can be used.",
      icon: "Icon",
      background: "Background",
    },

    // Leaderboard
    leaderboard: {
      title: "Leaderboard",
      thisWeek: "This Week",
      thisMonth: "This Month",
      allTime: "All Time",
      yourRank: "Your Rank",
      you: "You",
      rankAriaLabel: "Rank {rank}",
      rankTitle: "#{rank}",
      noRankLastWeek: "No rank last week",
      noRankLastMonth: "No rank last month",
      alreadyClaimed: "Already claimed",
      tokensAwarded: "+{count} tokens!",
      noReward: "No reward",
      claimFailed: "Claim failed",
      claimReward: "Claim Reward",
      claimed: "Claimed",
      claimNow: "Claim Now",
      claimedThisPeriod: "Claimed this period",
      notEligible: "Not eligible",
      learnMore: "Learn more",
      attempts: "attempts",
      questions: "questions",
      seeHowYouRank: "See how you rank against other students",
      noDataYet: "No data yet",
      beFirstComplete: "Be the first to complete a quiz!",
      howRankingsWork: "How rankings work:",
      averageScoreLast7: "Average score from all attempts in the last 7 days",
      averageScoreLast30: "Average score from all attempts in the last 30 days",
      overallAccuracyAllTime: "Overall accuracy across all attempts ever",
      formLevel: "S4/S5/S6 = form level",
      flameStreak: "Flame = consecutive study days",
    },

    // Token Log
    tokenLog: {
      title: "Token History",
      subtitle: "Track your earnings and purchases",
      totalEarned: "Total Earned",
      totalSpent: "Total Spent",
      allTransactions: "All Transactions",
      gains: "Gains",
      spends: "Spends",
      recentTransactionsCount: "Recent Transactions ({count})",
      noTransactionsYet: "No transactions yet",
      noEarningsYet: "No earnings yet",
      noPurchasesYet: "No purchases yet",
      completeQuizzesToEarn: "Complete quizzes to start earning tokens!",
      balanceAfterTokens: "Balance after: {balance} tokens",
      unknown: "Unknown",
    },

    // Calendar / Study Planner
    calendar: {
      addEvent: "Add Event",
      addEventSubtitle: "Schedule an exam or quiz and get a smart study plan",
      addExamQuiz: "Add Exam/Quiz",
      addAnotherEvent: "Add Another Event",
      today: "Today",
      studyPlannerTitle: "Study Planner",
      studyPlannerSubtitle: "Smart scheduling with spaced repetition",
      eventTypes: "Event Types",
      eventTypeMajorExam: "Major Exam",
      eventTypeSmallQuiz: "Small Quiz",
      eventTypeStudySuggestion: "Study Suggestion",
      eventTypeMistakeReview: "Mistake Review",
      eventTypeCompletedActivity: "Completed",
      eventsCount: "{count} event{plural}",
      scheduledEventsCount: "{count} scheduled event{plural}",
      noEventsScheduled: "No events scheduled",

      smartStudyCalendar: "Smart Study Calendar",
      smartStudyCalendarFeatures: "Smart Study Calendar features",
      srsReviewSystemTitle: "SRS review system",
      srsReviewSystemDesc: "Uses spaced repetition events to bring back questions/topics when you’re most likely to forget.",
      aiSuggestionsByTopicTitle: "AI suggestions (by topic)",
      aiSuggestionsByTopicDesc: "Suggestions are generated from your accuracy trends per topic/subtopic. Accepting one adds a study session into your calendar.",
      examQuizRevisionPlanTitle: "Exam / quiz / revision plan",
      examQuizRevisionPlanDesc: "Add exams and quizzes, then follow a plan that spreads practice and revision across days for steady progress.",
      mechanicsTitle: "Mechanics",
      mechanicsDesc: "Tap a day to see planned items and completions. Completed sessions turn green and stay visible for tracking.",
      aiStudyRecommendations: "AI Study Recommendations",
      suggestionsCount: "{count} suggestions",
      suggestedLabel: "Suggested",
      currentLabel: "Current",
      addToCalendar: "Add to calendar",
      dismiss: "Dismiss",
      review: "Review",
      aiLabel: "AI",
      doneCount: "{count} Done",
      timeMinsSecs: "{m}m {s}s",
      timeSecs: "{s}s",
      thisTopic: "this topic",
      questionsStillLoading: "Questions are still loading. Please wait a moment and try again.",
      noReviewSessionsFoundForDay: "No review sessions found for this day.",
      questionsNotFound: "Questions not found in database.",
      failedStartReviewTryAgain: "Failed to start review. Please try again.",
      failedStartStudySessionTryAgain: "Failed to start study session. Please try again.",
      aiRecommendationAddedSuccess: "✅ AI recommendation added to your calendar!",
      failedAddRecommendationWithReason: "Failed to add recommendation to calendar:\n\n{reason}",
      eventTypeEvent: "Event",
      deleteEventConfirm: "Delete this {eventType}? This will also remove all linked study suggestions and reviews.",
      eventDeletedSuccess: "Event deleted successfully!",
      failedDeleteEventWithReason: "Failed to delete event: {reason}",
      mcqCount: "{count} MCQs",
      noQuestionsAvailableForTopicSubtopic: "No questions available for {topic}{subtopic}.",
      noQuestionsAvailableForSuggestion: "No questions available for {topic}{subtopic}.\n\nPlease check that your question database includes this topic.",
      studySessionPreviewTitle: "Study Session Preview",
      phaseLabel: "Phase",
      scheduledEvents: "Scheduled Events",
      legendQuiz: "Quiz",
      legendStudyPlan: "Study Plan",
      legendAiSuggestion: "AI Suggestion",

      weekdaySunShort: "Sun",
      weekdayMonShort: "Mon",
      weekdayTueShort: "Tue",
      weekdayWedShort: "Wed",
      weekdayThuShort: "Thu",
      weekdayFriShort: "Fri",
      weekdaySatShort: "Sat",

      eventType: "Event Type",
      eventTypeRequired: "Event Type *",
      majorExam: "Major Exam",
      majorExamDesc: "10-day study plan with scaled intensity",
      smallQuiz: "Small Quiz",
      smallQuizDesc: "3-day focused review plan",

      examQuizDate: "Exam/Quiz Date",
      dateInputPlaceholder: "MM/DD or YYYY/MM/DD (e.g., 12/25 or 2024/12/25)",
      dateQuickLabel: "Quick:",
      dateFullLabel: "Full:",
      invalidDateHelp: "Please enter a valid date:\n\n• MM/DD (uses current year)\n• YYYY/MM/DD (specific year)\n\nExamples: 12/25 or 2024/12/25",
      pastDateWarningConfirm: "Warning: This date is in the past.\n\nDo you want to continue anyway?",

      filterTopicsSubtopics: "Filter Topics & Subtopics",
      topicsCount: "Topics ({selected}/{total})",
      topicsCountFull: "{selected}/{total} topic{plural}",
      subtopicsCount: "Subtopics ({selected}/{total})",
      subtopicsCountFull: "{selected}/{total} subtopic{plural}",
      selectAllTopicsUpToTitle: "Select all topics up to and including \"{topic}\"",
      selectAllSubtopicsUpToTitle: "Select all subtopics up to and including \"{subtopic}\"",
      upToHint: "Click \"Up to\" to select all topics up to that item",
      subtopicsAutoFilterHint: "Subtopics auto-filter based on selected topics",
      selectTopicsToFilterSubtopics: "Select topics to filter subtopics",
      noSubtopicsAvailable: "No subtopics available",

      customTitle: "Custom Title",
      autoTitlePlaceholder: "Auto: {title}",
      comprehensiveExam: "Comprehensive Exam",
      comprehensiveQuiz: "Comprehensive Quiz",
      topicsExamTitle: "{topics}{ellipsis} Exam",
      topicsQuizTitle: "{topics}{ellipsis} Quiz",

      autoGeneratedStudyPlan: "Auto-Generated Study Plan",
      planMajor10to7Label: "10-7 days before:",
      planMajor10to7Desc: "10 MCQs/day (Warm-up)",
      planMajor6to4Label: "6-4 days before:",
      planMajor6to4Desc: "20 MCQs/day (Consolidation)",
      planMajor3to1Label: "3-1 days before:",
      planMajor3to1Desc: "40 MCQs/day (Sprint Intensity)",
      planSmall3Label: "3 days before:",
      planSmall3Desc: "5 MCQs (Initial Review)",
      planSmall2Label: "2 days before:",
      planSmall2Desc: "10 MCQs (Topic Focus)",
      planSmall1Label: "1 day before:",
      planSmall1Desc: "15 MCQs (Final Polish)",
      focusLabel: "Focus:",
      allTopics: "All Topics",
      topicCountLabel: "{count} topic",
      subtopicCountLabel: "{count} subtopic",

      creating: "Creating...",
      createEventAndStudyPlan: "Create Event & Study Plan",
      eventCreatedSuccess: "Event created successfully!",
      failedCreateEventWithReason: "Failed to create event:\n\n{reason}",

      pleaseFillRequiredFields: "Please fill in all required fields",
      automaticPrepSuggestionsWillBeGenerated: "Automatic prep suggestions will be generated",
      titleRequired: "Title *",
      titlePlaceholder: "e.g., Chemistry Midterm Exam",
      dateRequired: "Date *",
      topicRequired: "Topic *",
      topicPlaceholder: "e.g., Organic Chemistry",
      subtopicOptional: "Subtopic (Optional)",
      subtopicPlaceholder: "e.g., Reaction Mechanisms",
      automaticSuggestions: "Automatic Suggestions:",
      automaticSuggestionsMajor: "Study plan with 10/20/40 MCQs (10-7, 6-4, 3-1 days before)",
      automaticSuggestionsSmall: "Quick review with 5-15 MCQs (3-1 days before)",
      createEvent: "Create Event",
      mcqCount: "{count} MCQs",
      clickToStartPractice: "Click to start practice →",
    },

    // Forum
    forum: {
      title: "The MCQ Forum",
      discuss: "Discuss",
      discussion: "Discussion",
      addComment: "Add Comment",
      editComment: "Edit Comment",
      deleteComment: "Delete Comment",
      noComments: "No comments yet. Be the first to discuss!",
      noCommentsYet: "No comments yet",
      beFirstToShareThoughts: "Be the first to share your thoughts!",
      loading: "Loading discussion...",
      connectDiscuss: "Connect and discuss with other students",
      notifications: "Notifications",
      markAllRead: "Mark all read",
      noNotificationsYet: "No notifications yet",
      postNotFound: "Post not found.",
      likedYourComment: "liked your comment",
      repliedToPost: "replied to your post",
      likedYourPost: "liked your post",
      likedYourReply: "liked your reply",
      repliedToComment: "replied to your comment",
      interactedWithContent: "interacted with your content",
      justNow: "Just now",
      mcqDiscussion: "MCQ Discussion",
      generalForum: "General Forum",
      searchQuestions: "Search questions, topics, DSE codes...",
      recent: "Recent",
      popular: "Popular",
      questionsWithDiscussions: "questions with discussions",
      noResultsFound: "No results found",
      noMcqDiscussions: "No MCQ discussions yet. Start one from any quiz!",
      comments: "comments",
      searchPosts: "Search posts...",
      all: "All",
      newPost: "New Post",
      noPosts: "No posts yet. Be the first!",
      createPost: "Create a Post",
      backToForum: "Back to forum",
      edited: "edited",
      save: "Save",
      cancel: "Cancel",
      replies: "Replies",
      writeReply: "Write a reply...",
      reply: "Reply",
      pleaseLoginReply: "Please log in to reply.",
      createNewPost: "Create New Post",
      category: "Category",
      title2: "Title",
      enterClearTitle: "Enter a clear, descriptive title",
      content: "Content",
      shareThoughts: "Share your thoughts, question, or announcement...",
      post: "Post",
      deletePost: "Delete this post?",
      deleteReply: "Delete this reply?",
      editExpired: "Edit window expired (15 min).",
      editWindowExpired: "Edit window expired",
      editExpiredLong: "Edit window has expired (15 minutes). You can no longer edit this comment.",
      editWindowLabel: "Edit window:",
      editLocked: "Edit locked",
      editIn: "Edit in {remaining}",
      confirmDeleteComment: "Are you sure you want to delete this comment?",
      failedDeleteComment: "Failed to delete comment",
      failedUpdateComment: "Failed to update comment",
      failedAddCommentWithReason: "Failed to add comment: {reason}",
      failedReplyWithReason: "Failed to reply: {reason}",
      pleaseLoginToLikeComments: "Please log in to like comments",
      pleaseLoginJoinDiscussion: "Please log in to join the discussion",
      shareYourThoughts: "Share your thoughts...",
      hideReplies: "Hide replies",
      commentsCount: "{count} Comments",
      timeAgoMinutes: "{count} min ago",
      timeAgoHours: "{count} hr ago",
      timeAgoDays: "{count} days ago",
      timeAgoMinutesShort: "{count}m",
      timeAgoHoursShort: "{count}h",
      timeAgoDaysShort: "{count}d",
    },
    
    // Mistake Notebook
    notebook: {
      // Main Navigation
      title: "Mistake Notebook",
      commandCenter: "Mistake Command Center",
      mistakeDeck: "Mistake Deck",
      learningInsights: "Learning Insights",
      learningAnalytics: "Learning Analytics",
      masteryArchive: "Mastery Archive",
      
      // Actions
      review: "Review Mistakes",
      practiceMistakes: "Practice Mistakes Only",
      practiceMistakesCount: "Practice {count} Mistake{plural}",
      practiceSelected: "Practice {count} Selected",
      cleared: "All mistakes cleared!",
      addedToNotebook: "Added to Mistake Notebook",
      removedFromNotebook: "Removed from Notebook",
      reviewMaster: "Review and master questions you got wrong",
      
      // Full Question Modal
      questionDetail: "Question Detail",
      question: "Question",
      options: "Options",
      viewFullQuestion: "View Full Question",
      viewFull: "View Full",
      attempts: "Attempts",
      masteryLevelLabel: "Mastery Level",
      lastAttemptedLabel: "Last Attempted",
      
      // Statistics
      totalMistakes: "Total Mistakes",
      topicsToFocus: "Topics to Focus",
      repeatedMistakes: "Repeated Mistakes",
      
      // Configurator
      configurePractice: "Configure Practice Session",
      numberOfQuestions: "Questions",
      questionsLabel: "1. Number of Questions",
      questionsAvailable: "available",
      questionsAvailableFull: "questions available with current filters",
      timeRange: "Time Range",
      timeRangeLabel: "2. Time Range (when you made the mistake)",
      allTime: "All Time",
      lastMonth: "Last Month",
      lastWeek: "Last Week",
      default: "default",
      
      // Filters
      topics: "Topics",
      topicsLabel: "3. Topics (leave empty for all)",
      subtopics: "Subtopics",
      subtopicsFilteredNote: "(filtered by selected topics)",
      masteryLevel: "Mastery Level",
      clearTopicFilter: "✕ Clear topic filter",
      clearSubtopicFilter: "Clear subtopic filter",
      clearMasteryFilter: "Clear mastery filter",
      filteredFrom: "Filtered from",
      clearSelection: "Clear Selection",
      
      // Mastery Status Labels
      masteryNew: "New",
      masteryDeveloping: "Developing",
      masteryProgressing: "Progressing",
      masteryNear: "Near-Mastery",
      masteryMastered: "Mastered",
      statusUnprocessed: "Unprocessed",
      statusInProgress: "In Progress",
      statusNearMastery: "Near Mastery",
      
      // Empty States
      allMistakes: "All Mistakes",
      noMistakesYet: "No mistakes yet!",
      keepPracticing: "Keep practicing. Wrong answers appear here.",
      startPracticing: "Start Practicing",
      noQuestionsFound: "No questions match your filters",
      tryAdjustFilters: "Try adjusting your filter settings",
      noArchivedYet: "No archived questions yet",
      archiveInstructions: "Answer 3 questions correctly to archive them",
      allCaughtUp: "All caught up!",
      
      // Question Details
      lastAttempt: "Last Attempt",
      missed: "Missed {count}×",
      yourAnswer: "Your Answer",
      correctAnswer: "Correct Answer",
      correct: "Correct",
      explanation: "Explanation",
      priority: "Priority",
      
      // How It Works
      howItWorks: "How it works",
      wrongAnswersAutoSaved: "Wrong answers are auto-saved here",
      useFilters: "Use filters to focus on specific topics or recent mistakes",
      practiceUntilMaster: "Practice until you master them!",
      clearAfterThreeCorrect: "✨ Questions automatically clear after 3 consecutive correct attempts!",
      
      // Loading States
      loadingMistakes: "Loading mistakes...",
      sessionLimited: "Session limited to {max} questions maximum.",
      
      // Topic Analysis
      topicBreakdown: "Topic Breakdown",
      hoverForDetails: "Hover over stats for details",
      weakTopics: "Weak Topics",
      focusTheseTopics: "Focus on these topics",
      repeatsByTopic: "Repeated Mistakes by Topic",
      needMorePractice: "Need more practice",
      improved: "Improved {count}",
      
      // Retention Dashboard
      retentionDashboard: "Retention Dashboard",
      addedThisWeek: "Added (7d)",
      masteredThisWeek: "Mastered (7d)",
      decayRate: "Decay Rate",
      decayImproving: "Improving",
      decayStable: "Stable",
      decayGrowing: "Growing",
      weakestSubtopics: "Weakest Subtopics",
      urgentReviews: "Urgent Reviews (by priority score)",
      
      // Priority Badge
      priorityScore: "Spaced Repetition Priority Score",
      
      // Metacognitive Tagging
      errorTypeLabel: "Error Type:",
      tagErrorType: "Tag Error Type",
      errorCategory: "Error Category",
      clearTag: "Clear tag",
      errorTypeMisread: "Misread Question",
      errorTypeConceptual: "Conceptual Gap",
      errorTypeCalculation: "Calculation Error",
      errorTypeCareless: "Careless Mistake",
      errorTypeVocab: "Vocabulary Gap",
      errorTypeDiagram: "Diagram Misread",
      errorMisread: "Misread Question",
      errorConceptual: "Conceptual Gap",
      errorCalculation: "Calculation Error",
      errorCareless: "Careless Mistake",
      errorVocabulary: "Vocabulary Gap",
      errorDiagram: "Diagram Misread",
      tagError: "Tag Error",
      
      // Extra Notes
      spacedRepetitionNote: "Cards sorted by Spaced Repetition priority — highest urgency first.",
      metacognitiveNote: "Tag each mistake with an Error Category to track your patterns.",
      
      // Learning Analytics Dashboard
      mistakeClearingActivity: "Mistake Clearing Activity",
      errorDensityByTopic: "Error Density by Topic",
      improvementTrend: "Improvement Trend (14 days)",
      selectedCount: "{count} selected",
      weekdaySunShort: "S",
      weekdayMonShort: "M",
      weekdayTueShort: "T",
      weekdayWedShort: "W",
      weekdayThuShort: "T",
      weekdayFriShort: "F",
      weekdaySatShort: "S",
      activityTooltipCleared: "{date}: {count} cleared",
      questionDiagramAlt: "Question diagram",
      clickTopicToFilter: "Click a topic to filter →",
      clickTopicsToFilter: "Click topics to filter (multi-select)",
      less: "Less",
      more: "More",
      
      // AI Daily Mission
      aiDailyMission: "AI Daily Mission",
      aiDailyMissionNote: "Smart AI selects 10 questions with interleaved practice to maximize retention.",
      needMoreQuestions: "Need 10+ mistakes (have {count})",
      interleavedPractice: "10 Questions • Interleaved Practice",
      
      // Timer Settings
      timerEnabled: "Timer Enabled",
      timedMode: "Timed Mode",
      
      // View Modes
      listView: "List View",
      kanbanView: "Kanban View",
      selectAll: "Select All",
      
      // Archive
      mastered: "Mastered",
      masteredOn: "Mastered {date}",
      archivedAt: "Archived at",
      
      // Filter Pills
      topicFilter: "Topic: {topic}",
    },
    
    // History
    history: {
      title: "Practice History",
      clickToSeeAnalysis: "Click any attempt to see the full analysis",
      viewingAttemptFromCalendar: "Viewing attempt from calendar",
      totalAttempts: "Total Attempts",
      averageScore: "Average Score",
      bestScore: "Best Score",
      totalTime: "Total Time",
      filtersAndSorting: "Filters & Sorting",
      timePeriod: "Time Period",
      allTime: "All Time",
      lastMonth: "Last Month",
      lastWeek: "Last Week",
      sortBy: "Sort By",
      recent: "Recent",
      score: "Score",
      time: "Time",
      yourAttempts: "Your Attempts",
      clickViewAnalysis: "Click to view full analysis",
      refresh: "Refresh",
      noAttemptsFound: "No attempts found",
      tryChangingFilter: "Try changing the filter period",
      startPracticingHistory: "Start practicing to see your history!",
      takeFirstQuiz: "Take Your First Quiz",
      correct: "correct",
      loadingHistory: "Loading your history...",
      timeHrsMins: "{h}h {m}m",
      timeMinsSecs: "{m}m {s}s",
      timeSecs: "{s}s",
    },

    firebaseTest: {
      title: "Firebase Connection Test",
      subtitle: "Diagnose data saving issues",
      runFirebaseTests: "Run Firebase Tests",
      runningTests: "Running Tests...",
      testResults: "Test Results",
      howToInterpretResults: "How to interpret results:",
      authLabel: "Auth",
      profileLabel: "Profile",
      saveAttemptLabel: "Save Attempt",
      fetchAttemptsLabel: "Fetch Attempts",
      leaderboardLabel: "Leaderboard",
      authInterpret: "Should show your email if logged in",
      profileInterpret: "Should load your user data from Firestore",
      saveAttemptInterpret: "Should successfully save a test quiz result",
      fetchAttemptsInterpret: "Should retrieve your quiz history",
      leaderboardInterpret: "Should load ranking data",
      commonIssues: "Common Issues:",
      issueNotAuthenticatedTitle: "Not authenticated:",
      issueNotAuthenticatedDesc: "Make sure you're logged in",
      issueFailedSaveFetchTitle: "Failed to save/fetch:",
      issueFailedSaveFetchDesc: "Check Firebase Firestore rules",
      issuePermissionDeniedTitle: "Permission denied:",
      issuePermissionDeniedDesc: "Update Firestore security rules to allow read/write",
      recommendedFirestoreRules: "Recommended Firestore Rules:",
      authenticatedAs: "Authenticated as {email}",
      notAuthenticated: "Not authenticated",
      profileLoadedWithAttempts: "Profile loaded ({count} attempts)",
      profileNotFound: "Profile not found",
      testAttemptSavedWithId: "Test attempt saved! ID: {id}",
      failedSaveAttemptWithReason: "Failed to save attempt: {reason}",
      skippedNotAuthenticated: "Skipped - not authenticated",
      fetchedAttemptsCount: "✅ Fetched {count} attempts",
      failedFetchAttemptsWithReason: "❌ Failed to fetch attempts: {reason}",
      leaderboardLoadedUsersCount: "✅ Leaderboard loaded ({count} users)",
      failedLoadLeaderboardWithReason: "❌ Failed to load leaderboard: {reason}",
    },

    // Common
    common: {
      loading: "Loading...",
      error: "Error",
      success: "Success",
      confirm: "Confirm",
      cancel: "Cancel",
      clear: "Clear",
      save: "Save",
      delete: "Delete",
      edit: "Edit",
      close: "Close",
      retry: "Retry",
      backToTopics: "Back to Topics",
      optional: "Optional",
      anonymous: "Anonymous",
      someone: "Someone",
      ninePlus: "9+",
      notAvailable: "N/A",
      ellipsis: "...",
      avatar: "Avatar",
    },

    // Authentication
    auth: {
      login: "Login",
      register: "Register",
      email: "Email Address",
      password: "Password",
      confirmPassword: "Confirm Password",
      fullName: "Full Name",
      createAccount: "Create Account",
      alreadyHaveAccount: "Already have an account?",
      dontHaveAccount: "Don't have an account?",
      loginHere: "Login here",
      registerHere: "Register here",
      welcomeBack: "Welcome Back",
      enterCredentials: "Enter your credentials to access your account",
      signingIn: "Signing in...",
      signIn: "Sign In",
      createAccountNow: "Create one now",
      secureLogin: "Secure login powered by Firebase Authentication",
      signInToContinue: "Sign in to continue",
      emailPlaceholder: "your.email@example.com",
      passwordPlaceholder: "••••••••",
      fullNamePlaceholder: "John Doe",
      noAccountFound: "No account found with this email.",
      incorrectPassword: "Incorrect password.",
      invalidEmail: "Invalid email address.",
      failedLogin: "Failed to log in. Please check your credentials.",
      joinCommunity: "Join our chemistry learning community",
      creatingAccount: "Creating account...",
      passwordsNoMatch: "Passwords do not match",
      passwordMinLength: "Password must be at least 6 characters",
      enterFullName: "Please enter your full name",
      emailAlreadyInUse: "An account with this email already exists.",
      weakPassword: "Password is too weak. Use at least 6 characters.",
      failedCreateAccount: "Failed to create account. Please try again.",
      minimumCharacters: "Minimum 6 characters",
      secureRegistration: "Secure registration powered by Firebase Authentication",
      switchToChinese: "Switch to Traditional Chinese",
      switchToEnglish: "Switch to English",
      languageNameChinese: "繁體中文",
      languageNameEnglish: "English",
    },

    // ChemStore
    store: {
      title: "ChemStore",
      subtitle: "Unlock exclusive items with your tokens",
      yourBalance: "Your Balance",
      profilePics: "Profile Pics",
      badges: "Badges",
      themes: "Themes",
      equipped: "Equipped",
      equip: "Equip",
      buy: "Buy",
      claim: "Claim",
      locked: "Locked",
      buying: "Buying...",
      comingSoon: "Coming soon! ",
      howToEarnTokens: "How to Earn Tokens",
      firstCorrect: "First-correct MCQ:",
      firstCorrectTokens: "2 tokens (per question, one-time)",
      correctedMistake: "Corrected mistake (Mistake/SRS review):",
      correctedMistakeTokens: "+1 token (per question, 24h cooldown)",
      quizBonus: "Quiz bonus (10+ questions):",
      quizBonusTokens: "100% = 20, 80%+ = 15, 50%+ = 10",
      leaderboardWeekly: "Leaderboard (weekly):",
      leaderboardWeeklyTokens: "#1=10, #2=9, #3=8, ...",
      leaderboardMonthly: "Leaderboard (monthly):",
      leaderboardMonthlyTokens: "Triple weekly rewards",
      studyStreaks: "Study Streaks:",
      studyStreaksTokens: "15 tokens (7 days) / 50 tokens (30 days)",
      notEnoughTokens: "Not enough tokens! ",
      purchased: "Purchased {name}! ",
      purchaseFailed: "Purchase failed",
      failedToEquip: "Failed to equip",
      pleaseTryAgain: "Please try again.",
      failedToEquipItem: "Failed to equip item",
    },

    // Practice Mode Selection
    practiceMode: {
      updateYourTopics: "Update Your Topics",
      learnedUpTo: "Learned Up To:",
      exceptions: "Exceptions (Not Learned):",
      saveChanges: "Save Changes",
      updating: "Updating...",
      topicsUpdated: "Topics updated successfully!",
      failedUpdate: "Failed to update topics",
      configureCustomSession: "Configure Custom Session",
      back: "Back",
      selectTopics: "1. Select Topics (Multi-choice)",
      lockedTopicsNotLearned: "Locked topics not yet learned. Update in Profile or click button above.",
      focusSubtopics: "2. Focus on Subtopics (Optional)",
      sessionLength: "3. Session Length",
      generateExam: "GENERATE EXAM",
      startPractice: "Start Practice",
    },
  },
  
  zh: {
    // 品牌
    appName: "ChemLeung HKDSE MCQ 練習平台",
    tagline: "HKDSE 化學練習",
    
    // 導航
    nav: {
      dashboard: "總覧",
      practice: "練習",
      leaderboard: "排行榜",
      history: "歷史記錄",
      profile: "個人資料",
      logout: "登出",
    },

    header: {
      tokens: "代幣",
      myHistory: "我的歷史",
      tokenHistory: "代幣歷史",
      logoutWarning: "您將登出帳戶。任何未儲存的進度將會遺失。",
      confirmLogoutInQuiz: "確定要登出嗎？\n\n⚠️ 您正在進行測驗，進度將會丟失！",
      confirmLeaveQuiz: "確定要離開測驗嗎？\n\n⚠️ 您目前的進度將會丟失！",
    },

    common: {
      loading: "載入中...",
      error: "錯誤",
      success: "成功",
      confirm: "確認",
      cancel: "取消",
      clear: "清除",
      save: "儲存",
      delete: "刪除",
      edit: "編輯",
      close: "關閉",
      retry: "重試",
      backToTopics: "返回主題",
      optional: "可選",
      anonymous: "匿名",
      someone: "某人",
      ninePlus: "9+",
      notAvailable: "不適用",
      ellipsis: "...",
      avatar: "頭像",
    },
    
    // 儀表板
    dashboard: {
      welcomeBack: "歡迎回來",
      totalAttempts: "總測驗次數",
      overallAccuracy: "整體準確率",
      questionsSolved: "已完成題目",
      correctAnswers: "正確答案",
      studyStreak: "連續學習天數",
      days: "天",
      startNewQuiz: "開始新測驗",
      viewLeaderboard: "查看排行榜",
      recentAttempts: "最近測驗",
      noAttempts: "尚未進行測驗！",
      takeFirstQuiz: "開始您的第一個測驗",
      browseForm: "瀏覽討論區",
      mistakeNotebook: "錯題簿",
      logout: "登出",
      confirmLogout: "確認登出",
      areYouSureLogout: "確定要登出嗎？",
      needSignInAgain: "您需要再次登入才能訪問您的帳戶並繼續練習。",
      cancel: "取消",
      errorLoadingAttempts: "載入記錄失敗",
      retry: "重試",
      clickRowFullAnalysis: "點擊記錄查看完整分析",
      refresh: "刷新",
      noDataYet: "暫無數據",
      completeQuizSeeResults: "完成測驗後記錄將顯示於此",
      correct: "正確",
      timeSpent: "用時",
      loadingDashboard: "載入總覧中...",

      howThisWorks: "運作方式",
      priorityReviewTitle: "優先重溫",
      top3UrgentMistakes: "最急需重溫的 3 題（ISRS 演算法）",
      priorityReviewEmpty: "暫未有記錄錯題。完成測驗並記錄錯題後，系統會提供個人化重溫建議！",
      priorityReviewMechanismTitle: "優先重溫機制",
      priorityReviewMechanismDesc: "此面板會根據 ISRS 優先分數顯示最急需重溫的 3 題錯題。",
      whatIncreasesPriorityTitle: "甚麼會提高優先度",
      whatIncreasesPriorityDesc: "近期答錯、重複錯誤，以及你最近學過的主題都會提高優先度。",
      whatQuickFixDoesTitle: "「快速修正」是甚麼",
      whatQuickFixDoesDesc: "立即開始針對該題的專注練習，讓你即時修正錯誤。",
      priorityCritical: "極高",
      priorityHigh: "高",
      priorityMedium: "中",
      priorityLabel: "{level} 優先",
      questionTextNotAvailable: "題目內容不可用",
      attempts: "嘗試",
      correct: "正確",
      quickFix: "快速修正",
      viewFullMistakeNotebook: "查看完整錯題簿",

      masteryHealthBarTitle: "掌握程度健康條",
      ruleOf3Subtitle: "基於「三次法則」系統",
      masteryHealthBarMechanismTitle: "掌握程度健康條機制",
      masteryMechanismDesc: "主題會按答對次數經歷 3 個狀態（「三次法則」）。",
      masteryNewTitle: "新",
      masteryNewDesc: "尚未嘗試",
      masteryImprovingTitle: "改善中",
      masteryImprovingDesc: "答對 1–2 次",
      masteryMasteredTitle: "已精通",
      masteryMasteredDesc: "答對 3 次或以上",
      masteryBarExplainer: "此健康條會把你的課程覆蓋度分成以上 3 類顯示。",
      syllabusCoverage: "課程覆蓋度",
      topicsTrackedCount: "已追蹤 {count} 個主題",
      unseenTooltip: "{pct}% 未開始（{count} 個主題）",
      improvingTooltip: "{pct}% 改善中（{count} 個主題）",
      masteredTooltip: "{pct}% 已精通（{count} 個主題）",

      quickStatsTitle: "快速統計",
      quickStatsMechanismTitle: "快速統計機制",
      quickStatsMechanismDesc: "此區域會一目了然地總結你的學習動力與進度。",
      quickStatsStudyStreakTitle: "連續學習",
      quickStatsStudyStreakDesc: "計算你連續學習的天數（根據近期活動）。",
      quickStatsTopicsMasteredTitle: "已精通主題",
      quickStatsTopicsMasteredDesc: "在掌握系統中達到「已精通」門檻的主題數量。",
      quickStatsInProgressTitle: "改善中",
      quickStatsInProgressDesc: "已開始但未精通的主題（繼續練習把它們推過門檻）。",

      quizSessionsCount: "{count} 次測驗",
      correctOutOfTotal: "{correct}/{total} 正確",
      clickAnyAttempt: "點擊任何一次測驗",
      toSeeDetailedAnalysis: "以查看詳細分析與洞見",

      priorityReviewAiStudySuggestionTitle: "優先重溫：AI 學習建議",
      aiStudySuggestionsEmpty: "暫未有 AI 建議。繼續練習以解鎖個人化建議。",
      aiStudySuggestionsMechanismTitle: "AI 學習建議",
      aiStudySuggestionsMechanismDesc: "這些建議會根據你近期在各主題／子主題的表現生成；接受後會把建議的學習時段加入你的日曆。",
    },

    srs: {
      title: "間隔重複重溫",
      failedLoadDueCardsTryAgain: "載入到期卡片失敗。請重試。",
      loadingDueCards: "載入到期卡片中...",
      pleaseSelectAtLeastOne: "請至少選擇一題進行重溫。",
      questionsStillLoading: "題目仍在載入中。請稍後再試。",

      questionsNeedReviewCount: "{count} 題需要重溫",
      reviewMode: "重溫模式",
      quickReview: "快速重溫",
      aiSelectsRandomQuestions: "AI 隨機選題",
      defaultBadge: "✓ 預設",
      singleQuestion: "單題重溫",
      reviewOneMistake: "重溫 1 題",
      customBatch: "自訂批次",
      selectSpecificCards: "選擇指定卡片",
      numberOfQuestions: "題數",
      nQuestions: "{count} 題",
      allCount: "全部（{count}）",

      timerSettings: "計時設定",
      enableTimer: "啟用計時",
      timedMode75sPerQuestion: "限時模式（每題 75 秒）",
      mustAnswerWithin75SecondsPerQuestion: "每題必須在 75 秒內作答",
      timerTracksSpeedNoLimit: "計時只用作記錄速度，不設時限",
      noTimerTracking: "不啟用計時",
      timedModeSummary75: "限時模式：75 秒／題",
      timerTrackingEnabled: "已啟用計時記錄",
      noTimer: "不計時",

      selectCardsToReview: "選擇要重溫的卡片",
      selectedCountOutOfTotal: "已選 {selected}／{total}",
      deselectAll: "取消全選",
      selectAll: "全選",
      dueLabel: "到期",
      noTopic: "無主題",
      noDueCardsMatchFilters: "沒有符合篩選條件的到期卡片",
      questionIdLabel: "題目 ID",
      intervalLabel: "間隔",
      attemptLabel: "次數",
      easeLabel: "易度",

      startQuickReviewCount: "開始快速重溫（{count} 題）",
      startSingleReview: "開始單題重溫",
      startBatchReviewCount: "開始批次重溫（{count} 題）",
    },

    practiceModeCarousel: {
      headerTitle: "選擇練習模式",
      headerSubtitle: "選擇一個模式開始你的學習之旅",
      previousMode: "上一個模式",
      nextMode: "下一個模式",
      startSession: "開始練習",
      clickToSelect: "點擊選擇",
      selectedLabel: "已選擇：{mode}",
      selectModeAria: "選擇 {mode}",

      timedTitle: "限時模式",
      timedSubtitle: "每題 1.25 分鐘",
      timedDesc: "最適合考試模擬",
      marathonTitle: "馬拉松模式",
      marathonSubtitle: "無時間壓力",
      marathonDesc: "慢慢做，專注理解",
      aiDailyTitle: "AI 每日任務",
      aiDailySubtitle: "智能間隔重複",
      aiDailyDesc: "AI 優化學習路徑",
      mistakeReviewTitle: "錯題重溫",
      mistakeReviewSubtitle: "針對弱點",
      mistakeReviewDesc: "練到完全掌握",
      customTitle: "自訂練習",
      customSubtitle: "由你決定",
      customDesc: "選擇主題與設定",
    },
    
    // 練習模式
    practice: {
      selectMode: "選擇練習模式",
      timed: "限時練習",
      timedDesc: "與時間競賽 - {minutes} 分鐘",
      marathon: "馬拉松模式",
      marathonDesc: "無限時間 - 追蹤您的進度",
      custom: "自定義練習",
      customDesc: "選擇主題和題目數量",
      startPractice: "開始練習",
      selectPracticeMode: "選擇練習模式",
      chooseHowPractice: "選擇您的練習方式",
      perQuestion: "分鐘每題",
      perfectForExam: "最適合考試模擬，帶有倒數計時器。",
      takeYourTime: "慢慢來。我們會記錄時間但沒有壓力！",
      chooseSpecificTopics: "選擇特定主題、子主題和題數。",
      questions: "題數：",
      configure: "設定",
      yourAvailableTopics: "您可用的主題",
      more: "更多",
      noTopicsConfigured: "尚未設定主題！",
      pleaseSetTopics: "請在個人資料設定中設定您已學習的主題。",
      goToProfile: "前往個人資料",
      updateTopics: "更新主題",
    },
    
    // 測驗介面
    quiz: {
      question: "題目",
      questionPrefix: "第",
      of: "共",
      flagQuestion: "標記題目",
      unflagQuestion: "取消標記",
      periodicTable: "元素週期表",
      periodicTableAlt: "元素週期表",
      overview: "總覽",
      previous: "上一題",
      next: "下一題",
      submit: "提交",
      answered: "已答",
      flagged: "已標記",
      skipped: "跳過",
      timeRemaining: "剩餘時間",
      sessionTime: "練習時間",
      totalTime: "總時間",
      initializingQuiz: "初始化測驗中...",
      type: "輸入",
      toSelect: "選擇",
      flag: "標記",
      tools: "工具",
      backToTopics: "返回主題",
      periodicTableOfElements: "元素週期表",
      time: "時間",
      thisQuestion: "本題時間：",
      questionOverview: "題目概覽",
      tip: "提示：",
      press: "按",
      pleaseAnswerAll: "請在提交前回答所有問題。",
      finishSubmit: "完成並提交",
      confirmBackToTopics: "確定要返回主題選擇嗎？\n\n⚠️ 您的所有進度將會丟失！",
      enableTimer: "啟用計時器",
      trackTimeSpent: "追蹤每題用時",
      showTimer: "顯示計時器",
      countdown: "倒數計時",
      timedMode: "限時模式",
      countdownTimer: "倒數計時並設時限",
      timeUp: "時間到！您的測驗將立即提交。",
    },
    
    // 成績
    results: {
      yourPerformance: "您的表現",
      totalTime: "總時間",
      averagePerQuestion: "每題平均時間",
      strengths: "優勢領域",
      needsFocus: "需要加強",
      detailedReview: "詳細檢討",
      yourAnswer: "您的答案",
      correctAnswer: "正確答案",
      explanation: "解釋",
      shareReport: "分享成績單",
      addToNotebook: "加入錯題簿",
      startNewSession: "開始新練習",
      savingToProfile: "保存至您的個人資料...",
      savedToProfile: "已保存至您的個人資料！",
      reviewsSaved: "已保存重溫記錄！",
      saveFailed: "保存失敗",
      continueAnyway: "仍然繼續",
      resultsSavingLeaveConfirm: "您的測驗結果仍在保存中。確定要離開嗎？",
      resultsMayNotBeSavedLeaveConfirm: "您的結果可能尚未完全保存。確定要離開嗎？",
      resultsNotSavedContinueAnywayConfirm: "您的結果未能保存。仍要繼續嗎？",
    },

    report: {
      shareReportCard: "分享成績單",
      downloadPngTitle: "下載為 PNG 圖片",
      downloadPdfTitle: "下載為 PDF",
      image: "圖片",
      pdf: "PDF",
      fileNamePrefix: "ChemLeung-Report",
      website: "www.chemleung.com",
      dismiss: "關閉",
      hkDsePracticeReport: "HKDSE 化學練習報告",
      studentName: "學生姓名",
      student: "學生",
      topicsCovered: "涵蓋主題",
      topicsUnit: "個主題",
      outOf: "/",
      correctLabel: "正確",
      correct: "正確",
      incorrect: "錯誤",
      timeUsed: "用時",
      timeHrsMins: "{h}小時 {m}分鐘",
      timeMinsSecs: "{m}分鐘 {s}秒",
      topicBreakdown: "主題分析",
      generatedBy: "由 ChemLeung HKDSE MCQ 練習平台生成",
      generating: "生成報告中...",
      mayTakeSeconds: "這可能需要幾秒鐘",
      reportNotReady: "報告未準備好。請重試。",
      failedCreateImage: "無法創建圖片",
      failedExportImageTryPdf: "匯出圖片失敗。請嘗試 PDF 匯出。",
      failedExportPdfTryImage: "匯出 PDF 失敗。請嘗試圖片匯出。",
      na: "不適用",
    },

    firebaseTest: {
      title: "Firebase 連線測試",
      subtitle: "診斷資料保存問題",
      runFirebaseTests: "執行 Firebase 測試",
      runningTests: "測試中...",
      testResults: "測試結果",
      howToInterpretResults: "💡 如何理解結果：",
      authLabel: "驗證",
      profileLabel: "個人資料",
      saveAttemptLabel: "保存記錄",
      fetchAttemptsLabel: "讀取記錄",
      leaderboardLabel: "排行榜",
      authInterpret: "若已登入，應顯示您的電郵",
      profileInterpret: "應能從 Firestore 載入您的用戶資料",
      saveAttemptInterpret: "應能成功保存一個測試測驗結果",
      fetchAttemptsInterpret: "應能讀取您的測驗歷史",
      leaderboardInterpret: "應能載入排名資料",
      commonIssues: "常見問題：",
      issueNotAuthenticatedTitle: "未登入：",
      issueNotAuthenticatedDesc: "請確認您已登入",
      issueFailedSaveFetchTitle: "保存/讀取失敗：",
      issueFailedSaveFetchDesc: "請檢查 Firebase Firestore 規則",
      issuePermissionDeniedTitle: "權限不足：",
      issuePermissionDeniedDesc: "更新 Firestore 安全規則以允許讀寫",
      recommendedFirestoreRules: "建議 Firestore 規則：",
      authenticatedAs: "已登入為 {email}",
      notAuthenticated: "未登入",
      profileLoadedWithAttempts: "已載入個人資料（{count} 次記錄）",
      profileNotFound: "找不到個人資料",
      testAttemptSavedWithId: "✅ 已保存測試記錄！ID：{id}",
      failedSaveAttemptWithReason: "❌ 保存記錄失敗：{reason}",
      skippedNotAuthenticated: "⚠️ 已跳過（未登入）",
      fetchedAttemptsCount: "✅ 已讀取 {count} 次記錄",
      failedFetchAttemptsWithReason: "❌ 讀取記錄失敗：{reason}",
      leaderboardLoadedUsersCount: "✅ 已載入排行榜（{count} 位用戶）",
      failedLoadLeaderboardWithReason: "❌ 載入排行榜失敗：{reason}",
    },
    
    // 認證
    auth: {
      login: "登入",
      register: "註冊",
      email: "電郵地址",
      password: "密碼",
      confirmPassword: "確認密碼",
      fullName: "全名",
      createAccount: "建立帳戶",
      alreadyHaveAccount: "已經有帳戶？",
      dontHaveAccount: "沒有帳戶？",
      loginHere: "在此登入",
      registerHere: "在此註冊",
      welcomeBack: "歡迎回來",
      enterCredentials: "輸入您的登入資料以進入帳戶",
      signingIn: "登入中...",
      signIn: "登入",
      createAccountNow: "立即建立",
      secureLogin: "由 Firebase 認證提供安全登入",
      signInToContinue: "登入以繼續",
      emailPlaceholder: "your.email@example.com",
      passwordPlaceholder: "••••••••",
      fullNamePlaceholder: "陳大文",
      noAccountFound: "此電郵未有對應帳戶。",
      incorrectPassword: "密碼錯誤。",
      invalidEmail: "電郵地址無效。",
      failedLogin: "登入失敗。請檢查登入資料。",
      joinCommunity: "加入我們的化學學習社群",
      creatingAccount: "建立帳戶中...",
      passwordsNoMatch: "密碼不相符",
      passwordMinLength: "密碼至少需要 6 個字符",
      enterFullName: "請輸入您的全名",
      emailAlreadyInUse: "此電郵已被使用。",
      weakPassword: "密碼太弱。請至少使用 6 個字符。",
      failedCreateAccount: "建立帳戶失敗。請重試。",
      minimumCharacters: "最少 6 個字符",
      secureRegistration: "由 Firebase 提供安全註冊",
      switchToChinese: "切換至繁體中文",
      switchToEnglish: "切換至英文",
      languageNameChinese: "繁體中文",
      languageNameEnglish: "英文",
    },

    profile: {
      profileSettings: "個人資料設定",
      yourStatistics: "您的統計",
      displayName: "顯示名稱",
      email: "電郵地址",
      schoolLevel: "年級（中四／中五／中六）",
      studyLevel: "目前學習程度",
      memberSince: "加入日期",
      saveChanges: "儲存變更",
      topicExceptions: "主題例外",
      unlockTopic: "解鎖主題",
      lockTopic: "鎖定主題",
      manageAccount: "管理您的帳戶與學習偏好",
      totalAttempts: "總測驗次數",
      overallAccuracy: "整體準確率",
      questionsSolved: "已完成題目",
      accountInformation: "帳戶資料",
      profileUpdated: "個人資料已成功更新！",
      failedUpdate: "更新個人資料失敗。請重試。",
      enterYourName: "輸入您的名稱",
      emailCannotChange: "電郵地址無法更改",
      selectCurrentForm: "選擇您目前年級（中四／中五／中六）",
      topicsLearnedUpTo: "已學習至主題",
      selectHighestTopic: "選擇您已學到的最高主題編號。例如：選擇「08」代表您已學習 01–08。",
      topicExceptionsLabel: "主題例外",
      clickToExclude: "點擊主題以從練習中排除",
      yourAvailableTopicsCount: "您可用的主題",
      theseTopicsWillAppear: "這些主題會出現在練習模式中",
      saving: "儲存中...",
      profilePicture: "個人頭像",
      preview: "預覽",
      onlyOwnedItems: "只能使用您擁有（或免費）的物品。",
      icon: "圖示",
      background: "背景",
    },

    notebook: {
      title: "錯題簿",
      commandCenter: "錯題指揮中心",
      mistakeDeck: "錯題卡組",
      learningInsights: "學習洞察",
      learningAnalytics: "學習分析",
      masteryArchive: "精通封存",

      review: "重溫錯題",
      practiceMistakes: "只練錯題",
      practiceMistakesCount: "練習 {count} 題錯題{plural}",
      practiceSelected: "練習已選 {count} 題",
      cleared: "所有錯題已清除！",
      addedToNotebook: "已加入錯題簿",
      removedFromNotebook: "已從錯題簿移除",
      reviewMaster: "重溫並精通您答錯的題目",

      questionDetail: "題目詳情",
      question: "題目",
      options: "選項",
      viewFullQuestion: "查看完整題目",
      viewFull: "查看完整",
      attempts: "嘗試次數",
      masteryLevelLabel: "掌握程度",
      lastAttemptedLabel: "最後嘗試",

      totalMistakes: "錯題總數",
      topicsToFocus: "需加強主題",
      repeatedMistakes: "重複錯題",

      configurePractice: "設定練習",
      numberOfQuestions: "題數",
      questionsLabel: "1. 題目數量",
      questionsAvailable: "可用",
      questionsAvailableFull: "在目前篩選條件下可用的題目",
      timeRange: "時間範圍",
      timeRangeLabel: "2. 時間範圍（何時出現錯題）",
      allTime: "全部",
      lastMonth: "最近一個月",
      lastWeek: "最近一週",
      default: "預設",

      topics: "主題",
      topicsLabel: "3. 主題（留空代表全部）",
      subtopics: "子主題",
      subtopicsFilteredNote: "（會隨已選主題篩選）",
      masteryLevel: "掌握程度",
      clearTopicFilter: "✕ 清除主題篩選",
      clearSubtopicFilter: "清除子主題篩選",
      clearMasteryFilter: "清除掌握程度篩選",
      filteredFrom: "篩選自",
      clearSelection: "清除選擇",

      masteryNew: "新",
      masteryDeveloping: "發展中",
      masteryProgressing: "進步中",
      masteryNear: "接近精通",
      masteryMastered: "已精通",
      statusUnprocessed: "未處理",
      statusInProgress: "進行中",
      statusNearMastery: "接近精通",

      allMistakes: "所有錯題",
      noMistakesYet: "暫無錯題！",
      keepPracticing: "繼續練習，答錯的題目會在此出現。",
      startPracticing: "開始練習",
      noQuestionsFound: "沒有題目符合篩選條件",
      tryAdjustFilters: "嘗試調整篩選設定",
      noArchivedYet: "尚未有封存題目",
      archiveInstructions: "連續答對 3 次即可自動封存",
      allCaughtUp: "已全部完成！",

      lastAttempt: "上次嘗試",
      missed: "錯 {count} 次",
      yourAnswer: "您的答案",
      correctAnswer: "正確答案",
      correct: "正確",
      explanation: "解釋",
      priority: "優先度",

      howItWorks: "運作方式",
      wrongAnswersAutoSaved: "答錯的題目會自動保存到此",
      useFilters: "使用篩選器專注於特定主題或近期錯題",
      practiceUntilMaster: "練到您真正掌握！",
      clearAfterThreeCorrect: "✨ 連續答對 3 次後，題目會自動清除！",

      loadingMistakes: "載入錯題中...",
      sessionLimited: "練習最多限制為 {max} 題。",

      topicBreakdown: "主題分析",
      hoverForDetails: "將滑鼠移到統計上查看詳情",
      weakTopics: "薄弱主題",
      focusTheseTopics: "專注於這些主題",
      repeatsByTopic: "按主題統計的重複錯題",
      needMorePractice: "需要更多練習",
      improved: "已改善 {count}",

      retentionDashboard: "記憶保留儀表板",
      addedThisWeek: "新增（7 天）",
      masteredThisWeek: "精通（7 天）",
      decayRate: "遺忘率",
      decayImproving: "改善中",
      decayStable: "穩定",
      decayGrowing: "上升",
      weakestSubtopics: "最薄弱子主題",
      urgentReviews: "最緊急重溫（按優先分數）",

      priorityScore: "間隔重複優先分數",

      errorTypeLabel: "錯誤類型：",
      tagErrorType: "標記錯誤類型",
      errorCategory: "錯誤分類",
      clearTag: "清除標記",
      errorTypeMisread: "看錯題目",
      errorTypeConceptual: "概念不足",
      errorTypeCalculation: "計算錯誤",
      errorTypeCareless: "粗心大意",
      errorTypeVocab: "詞彙不足",
      errorTypeDiagram: "看錯圖表",
      errorMisread: "看錯題目",
      errorConceptual: "概念不足",
      errorCalculation: "計算錯誤",
      errorCareless: "粗心大意",
      errorVocabulary: "詞彙不足",
      errorDiagram: "看錯圖表",
      tagError: "標記錯誤",

      spacedRepetitionNote: "卡片按間隔重複優先度排序——越緊急越前。",
      metacognitiveNote: "為每題錯題標記錯誤分類，以追蹤您的常見模式。",

      mistakeClearingActivity: "錯題清除活動",
      errorDensityByTopic: "按主題的錯誤密度",
      improvementTrend: "改善趨勢（14 天）",
      selectedCount: "已選 {count}",
      weekdaySunShort: "日",
      weekdayMonShort: "一",
      weekdayTueShort: "二",
      weekdayWedShort: "三",
      weekdayThuShort: "四",
      weekdayFriShort: "五",
      weekdaySatShort: "六",
      activityTooltipCleared: "{date}：清除 {count} 題",
      questionDiagramAlt: "題目圖表",
      clickTopicToFilter: "點擊主題以篩選 →",
      clickTopicsToFilter: "點擊主題以篩選（可多選）",
      less: "較少",
      more: "較多",

      aiDailyMission: "AI 每日任務",
      aiDailyMissionNote: "AI 會智能挑選 10 題並穿插練習，以最大化記憶保留。",
      needMoreQuestions: "需要 10+ 道錯題（目前 {count}）",
      interleavedPractice: "10 題 • 穿插練習",

      timerEnabled: "啟用計時器",
      timedMode: "限時模式",

      listView: "清單檢視",
      kanbanView: "看板檢視",
      selectAll: "全選",

      mastered: "已精通",
      masteredOn: "於 {date} 精通",
      archivedAt: "封存於",

      topicFilter: "主題：{topic}",
    },

    leaderboard: {
      title: "排行榜",
      thisWeek: "本週",
      thisMonth: "本月",
      allTime: "全期",
      yourRank: "您的排名",
      you: "你",
      rankAriaLabel: "排名 {rank}",
      rankTitle: "#{rank}",
      noRankLastWeek: "上週沒有排名",
      noRankLastMonth: "上月沒有排名",
      alreadyClaimed: "已領取",
      tokensAwarded: "+{count} 代幣！",
      noReward: "沒有獎勵",
      claimFailed: "領取失敗",
      claimReward: "領取獎勵",
      claimed: "已領取",
      claimNow: "立即領取",
      claimedThisPeriod: "本期已領取",
      notEligible: "不符合資格",
      learnMore: "了解更多",
      attempts: "次",
      questions: "題",
      seeHowYouRank: "看看你在其他同學中的排名",
      noDataYet: "暫無數據",
      beFirstComplete: "成為第一個完成測驗的人！",
      howRankingsWork: "排名如何計算：",
      averageScoreLast7: "最近 7 天內所有測驗的平均分",
      averageScoreLast30: "最近 30 天內所有測驗的平均分",
      overallAccuracyAllTime: "所有歷史測驗的整體準確率",
      formLevel: "S4/S5/S6 = 年級",
      flameStreak: "火焰 = 連續學習天數",
    },

    calendar: {
      smartStudyCalendar: "智能學習日曆",
      smartStudyCalendarFeatures: "智能學習日曆功能",
      srsReviewSystemTitle: "SRS 重溫系統",
      srsReviewSystemDesc: "透過間隔重複提醒你在最容易忘記的時候重溫題目／主題。",
      aiSuggestionsByTopicTitle: "AI 建議（按主題）",
      aiSuggestionsByTopicDesc: "建議會根據你在各主題／子主題的準確率趨勢生成；接受後會把學習時段加入日曆。",
      examQuizRevisionPlanTitle: "考試／小測／溫習計劃",
      examQuizRevisionPlanDesc: "新增考試和小測，跟隨跨日分配的練習與溫習計劃，穩步進步。",
      mechanicsTitle: "操作方式",
      mechanicsDesc: "點擊日期可查看安排與完成情況；完成的學習時段會變綠並保留作追蹤。",
      aiStudyRecommendations: "AI 學習建議",
      suggestionsCount: "{count} 個建議",
      suggestedLabel: "建議日期",
      currentLabel: "目前",
      addToCalendar: "加入日曆",
      dismiss: "略過",
      review: "重溫",
      aiLabel: "AI",
      doneCount: "完成 {count}",
      timeMinsSecs: "{m}分 {s}秒",
      timeSecs: "{s}秒",
      thisTopic: "此主題",
      questionsStillLoading: "題目仍在載入中。請稍後再試。",
      noReviewSessionsFoundForDay: "此日沒有重溫時段。",
      questionsNotFound: "找不到題目資料庫中的題目。",
      failedStartReviewTryAgain: "開始重溫失敗。請重試。",
      failedStartStudySessionTryAgain: "開始學習時段失敗。請重試。",
      aiRecommendationAddedSuccess: "✅ 已把 AI 建議加入日曆！",
      failedAddRecommendationWithReason: "加入建議到日曆失敗：\n\n{reason}",
      eventTypeEvent: "活動",
      deleteEventConfirm: "刪除這個{eventType}？這將同時移除所有相關的學習建議與重溫。",
      eventDeletedSuccess: "活動已刪除！",
      failedDeleteEventWithReason: "刪除活動失敗：{reason}",
      mcqCount: "{count} 題 MCQ",
      noQuestionsAvailableForTopicSubtopic: "{topic}{subtopic} 沒有可用題目。",
      noQuestionsAvailableForSuggestion: "{topic}{subtopic} 沒有可用題目。\n\n請確認題庫包含此主題。",
      studySessionPreviewTitle: "學習時段預覽",
      phaseLabel: "階段",
      scheduledEvents: "已安排活動",
      legendQuiz: "小測",
      legendStudyPlan: "學習計劃",
      legendAiSuggestion: "AI 建議",
      addEvent: "新增活動",
      addEventSubtitle: "安排考試或小測並獲得智能溫習計劃",
      addExamQuiz: "新增考試／小測",
      addAnotherEvent: "新增另一個活動",
      today: "今天",
      studyPlannerTitle: "學習計劃",
      studyPlannerSubtitle: "以間隔重複為基礎的智能排程",
      eventTypes: "活動類型",
      eventTypeMajorExam: "大型考試",
      eventTypeSmallQuiz: "小測",
      eventTypeStudySuggestion: "溫習建議",
      eventTypeMistakeReview: "錯題重溫",
      eventTypeCompletedActivity: "已完成",
      eventsCount: "{count} 個活動{plural}",
      scheduledEventsCount: "{count} 個已排程活動{plural}",
      noEventsScheduled: "尚未安排活動",

      weekdaySunShort: "日",
      weekdayMonShort: "一",
      weekdayTueShort: "二",
      weekdayWedShort: "三",
      weekdayThuShort: "四",
      weekdayFriShort: "五",
      weekdaySatShort: "六",

      eventType: "活動類型",
      eventTypeRequired: "活動類型 *",
      majorExam: "大型考試",
      majorExamDesc: "10 天溫習計劃（循序加強）",
      smallQuiz: "小測",
      smallQuizDesc: "3 天重點溫習計劃",

      examQuizDate: "考試／小測日期",
      dateInputPlaceholder: "MM/DD 或 YYYY/MM/DD（例如：12/25 或 2024/12/25）",
      dateQuickLabel: "快速：",
      dateFullLabel: "完整：",
      invalidDateHelp: "請輸入有效日期：\n\n• MM/DD（使用本年度）\n• YYYY/MM/DD（指定年份）\n\n例子：12/25 或 2024/12/25",
      pastDateWarningConfirm: "提示：此日期已過去。\n\n仍要繼續嗎？",

      filterTopicsSubtopics: "篩選主題與子主題",
      topicsCount: "主題（{selected}/{total}）",
      topicsCountFull: "{selected}/{total} 個主題{plural}",
      subtopicsCount: "子主題（{selected}/{total}）",
      subtopicsCountFull: "{selected}/{total} 個子主題{plural}",
      selectAllTopicsUpToTitle: "選取直到並包括「{topic}」的所有主題",
      selectAllSubtopicsUpToTitle: "選取直到並包括「{subtopic}」的所有子主題",
      upToHint: "點擊「到此為止」以選取直到該項目",
      subtopicsAutoFilterHint: "子主題會按已選主題自動篩選",
      selectTopicsToFilterSubtopics: "請先選擇主題以篩選子主題",
      noSubtopicsAvailable: "沒有可用子主題",

      customTitle: "自訂標題",
      autoTitlePlaceholder: "自動：{title}",
      comprehensiveExam: "綜合考試",
      comprehensiveQuiz: "綜合小測",
      topicsExamTitle: "{topics}{ellipsis} 考試",
      topicsQuizTitle: "{topics}{ellipsis} 小測",

      autoGeneratedStudyPlan: "自動生成溫習計劃",
      planMajor10to7Label: "距離 10–7 天：",
      planMajor10to7Desc: "每日 10 題（熱身）",
      planMajor6to4Label: "距離 6–4 天：",
      planMajor6to4Desc: "每日 20 題（鞏固）",
      planMajor3to1Label: "距離 3–1 天：",
      planMajor3to1Desc: "每日 40 題（衝刺）",
      planSmall3Label: "距離 3 天：",
      planSmall3Desc: "5 題（初步重溫）",
      planSmall2Label: "距離 2 天：",
      planSmall2Desc: "10 題（主題集中）",
      planSmall1Label: "距離 1 天：",
      planSmall1Desc: "15 題（最後整理）",
      focusLabel: "重點：",
      allTopics: "所有主題",
      topicCountLabel: "{count} 個主題",
      subtopicCountLabel: "{count} 個子主題",

      creating: "建立中...",
      createEventAndStudyPlan: "建立活動及溫習計劃",
      eventCreatedSuccess: "活動已成功建立！",
      failedCreateEventWithReason: "建立活動失敗：\n\n{reason}",

      pleaseFillRequiredFields: "請填寫所有必填欄位",
      automaticPrepSuggestionsWillBeGenerated: "將會自動生成準備建議",
      titleRequired: "標題 *",
      titlePlaceholder: "例如：化學中期考試",
      dateRequired: "日期 *",
      topicRequired: "主題 *",
      topicPlaceholder: "例如：有機化學",
      subtopicOptional: "子主題（可選）",
      subtopicPlaceholder: "例如：反應機理",
      automaticSuggestions: "自動建議：",
      automaticSuggestionsMajor: "10/20/40 題溫習計劃（距離 10–7、6–4、3–1 天）",
      automaticSuggestionsSmall: "快速重溫 5–15 題（距離 3–1 天）",
      createEvent: "建立活動",
      mcqCount: "{count} 題 MCQ",
      clickToStartPractice: "點擊開始練習 →",
    },

    forum: {
      title: "MCQ 討論區",
      discuss: "討論",
      discussion: "討論",
      addComment: "新增留言",
      editComment: "編輯留言",
      deleteComment: "刪除留言",
      noComments: "尚未有留言。做第一個討論的人吧！",
      noCommentsYet: "尚未有留言",
      beFirstToShareThoughts: "做第一個分享想法的人吧！",
      loading: "載入討論中...",
      connectDiscuss: "與其他同學交流討論",
      notifications: "通知",
      markAllRead: "全部標為已讀",
      noNotificationsYet: "暫無通知",
      postNotFound: "找不到帖子。",
      likedYourComment: "讚了你的留言",
      repliedToPost: "回覆了你的帖子",
      likedYourPost: "讚了你的帖子",
      likedYourReply: "讚了你的回覆",
      repliedToComment: "回覆了你的留言",
      interactedWithContent: "與你的內容互動",
      justNow: "剛剛",
      mcqDiscussion: "MCQ 討論",
      generalForum: "一般討論",
      searchQuestions: "搜尋題目、主題、DSE 題號...",
      recent: "最新",
      popular: "熱門",
      questionsWithDiscussions: "題有討論",
      noResultsFound: "找不到結果",
      noMcqDiscussions: "尚未有 MCQ 討論。可從任何測驗開始討論！",
      comments: "留言",
      searchPosts: "搜尋帖子...",
      all: "全部",
      newPost: "新帖子",
      noPosts: "尚未有帖子。做第一個吧！",
      createPost: "建立帖子",
      backToForum: "返回討論區",
      edited: "已編輯",
      save: "儲存",
      cancel: "取消",
      replies: "回覆",
      writeReply: "撰寫回覆...",
      reply: "回覆",
      pleaseLoginReply: "請登入以回覆。",
      createNewPost: "建立新帖子",
      category: "分類",
      title2: "標題",
      enterClearTitle: "輸入清晰、具描述性的標題",
      content: "內容",
      shareThoughts: "分享你的想法、問題或公告...",
      post: "發佈",
      deletePost: "刪除這個帖子？",
      deleteReply: "刪除這個回覆？",
      editExpired: "可編輯時間已過（15 分鐘）。",
      editWindowExpired: "編輯期限已過",
      editExpiredLong: "可編輯時間已過（15 分鐘），你不能再編輯此留言。",
      editWindowLabel: "可編輯時間：",
      editLocked: "已鎖定編輯",
      editIn: "{remaining} 後可編輯",
      confirmDeleteComment: "確定要刪除這則留言嗎？",
      failedDeleteComment: "刪除留言失敗",
      failedUpdateComment: "更新留言失敗",
      failedAddCommentWithReason: "新增留言失敗：{reason}",
      failedReplyWithReason: "回覆失敗：{reason}",
      pleaseLoginToLikeComments: "請登入以讚好留言",
      pleaseLoginJoinDiscussion: "請登入以加入討論",
      shareYourThoughts: "分享你的想法...",
      hideReplies: "隱藏回覆",
      commentsCount: "{count} 則留言",
      timeAgoMinutes: "{count} 分鐘前",
      timeAgoHours: "{count} 小時前",
      timeAgoDays: "{count} 天前",
      timeAgoMinutesShort: "{count}分",
      timeAgoHoursShort: "{count}小時",
      timeAgoDaysShort: "{count}天",
    },

    history: {
      title: "練習歷史",
      clickToSeeAnalysis: "點擊任何記錄以查看完整分析",
      viewingAttemptFromCalendar: "正在查看從日曆開啟的記錄",
      totalAttempts: "總測驗次數",
      averageScore: "平均分",
      bestScore: "最高分",
      totalTime: "總用時",
      filtersAndSorting: "篩選與排序",
      timePeriod: "時間範圍",
      allTime: "全部",
      lastMonth: "最近一個月",
      lastWeek: "最近一週",
      sortBy: "排序方式",
      recent: "最新",
      score: "分數",
      time: "時間",
      yourAttempts: "您的記錄",
      clickViewAnalysis: "點擊查看完整分析",
      refresh: "刷新",
      noAttemptsFound: "找不到記錄",
      tryChangingFilter: "嘗試更改時間範圍",
      startPracticingHistory: "開始練習以在此查看歷史記錄！",
      takeFirstQuiz: "開始第一個測驗",
      correct: "正確",
      loadingHistory: "載入歷史記錄中...",
      timeHrsMins: "{h}小時 {m}分鐘",
      timeMinsSecs: "{m}分鐘 {s}秒",
      timeSecs: "{s}秒",
    },

    store: {
      title: "ChemStore",
      subtitle: "使用代幣解鎖專屬物品",
      yourBalance: "您的餘額",
      profilePics: "頭像",
      badges: "徽章",
      themes: "主題",
      equipped: "已裝備",
      equip: "裝備",
      buy: "購買",
      claim: "領取",
      locked: "未解鎖",
      buying: "購買中...",
      comingSoon: "即將推出！",
      howToEarnTokens: "如何獲得代幣",
      firstCorrect: "首次答對：",
      firstCorrectTokens: "每題 2 代幣（一次性）",
      correctedMistake: "改正錯題（錯題簿／SRS 重溫）：",
      correctedMistakeTokens: "每題 +1 代幣（24 小時冷卻）",
      quizBonus: "測驗獎勵（10 題或以上）：",
      quizBonusTokens: "100% = 20，80%+ = 15，50%+ = 10",
      leaderboardWeekly: "排行榜（每週）：",
      leaderboardWeeklyTokens: "第 1=10，第 2=9，第 3=8，...",
      leaderboardMonthly: "排行榜（每月）：",
      leaderboardMonthlyTokens: "每週獎勵的 3 倍",
      studyStreaks: "學習連續：",
      studyStreaksTokens: "7 天 15 代幣／30 天 50 代幣",
      notEnoughTokens: "代幣不足！",
      purchased: "已購買 {name}！",
      purchaseFailed: "購買失敗",
      failedToEquip: "裝備失敗",
      pleaseTryAgain: "請再試一次。",
      failedToEquipItem: "裝備物品失敗",
    },

    tokenLog: {
      title: "代幣歷史",
      subtitle: "查看你的獲得與消費記錄",
      totalEarned: "總獲得",
      totalSpent: "總消費",
      allTransactions: "全部交易",
      gains: "收入",
      spends: "支出",
      recentTransactionsCount: "最近交易（{count}）",
      noTransactionsYet: "暫無交易",
      noEarningsYet: "暫無收入",
      noPurchasesYet: "暫無消費",
      completeQuizzesToEarn: "完成測驗即可開始賺取代幣！",
      balanceAfterTokens: "交易後餘額：{balance} 代幣",
      unknown: "未知",
    },

    // Practice Mode Selection
    practiceMode: {
      updateYourTopics: "更新您的主題",
      learnedUpTo: "已學習至：",
      exceptions: "例外（未學習）：",
      saveChanges: "儲存變更",
      updating: "更新中...",
      topicsUpdated: "主題已成功更新！",
      failedUpdate: "更新主題失敗",
      configureCustomSession: "自訂練習設定",
      back: "返回",
      selectTopics: "1. 選擇主題（可多選）",
      lockedTopicsNotLearned: "鎖定的主題尚未學習。請在個人資料中更新或點擊上方按鈕。",
      focusSubtopics: "2. 選擇子主題（可選）",
      sessionLength: "3. 練習題數",
      generateExam: "開始練習",
      startPractice: "開始練習",
    },
  },
};

// ...

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('chemleung_language') || 'en';
  });

  useEffect(() => {
    localStorage.setItem('chemleung_language', language);
  }, [language]);

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'en' ? 'zh' : 'en');
  };

  const t = (key) => {
    const keys = key.split('.');
    let value = translations[language];
    for (const k of keys) {
      if (value && typeof value === 'object') {
        value = value[k];
      } else {
        return key;
      }
    }
    return value || key;
  };

  const tf = (key, params = {}) => {
    let text = t(key);
    Object.keys(params).forEach(param => {
      text = text.replace(`{${param}}`, params[param]);
    });
    return text;
  };

  const value = {
    language,
    setLanguage,
    toggleLanguage,
    t,
    tf,
    isEnglish: language === 'en',
    isChinese: language === 'zh',
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}